/**
 * anyaHelpKnowledge.js — Server-side help knowledge for Anya.
 *
 * This module mirrors the frontend helpRegistry data as an ES module so Anya can
 * answer questions about any page, feature, or field
 * with accurate, up-to-date structured data.
 */

export const CURRENT_TOUR_VERSION = 1
export const CURRENT_MANUAL_VERSION = 1

/**
 * Canonical help data for every page in GrantFlow (mirrors src/config/helpRegistry.js).
 * Keys must match routeNames from navConfig.js.
 */
export const HELP_REGISTRY = [
  {
    key: 'Dashboard',
    route: '/Dashboard',
    navGroup: 'home',
    title: 'Dashboard',
    description: 'Your home base: overview of grants, deadlines, and activity. Jump back here anytime.',
    purpose: 'Get a snapshot of your grant pipeline, upcoming deadlines, and recent activity in one place.',
    whoCanUse: 'all',
    mainActions: ['View grant pipeline summary', 'Check upcoming deadlines', 'Access quick links to common tasks'],
    relatedFeatures: ['Calendar', 'Pipeline', 'GrantDeadline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Calendar',
    route: '/Calendar',
    navGroup: 'home',
    title: 'Calendar',
    description: 'See grant deadlines and key dates in a calendar view.',
    purpose: 'Visualise all grant deadlines and activity on a monthly/weekly calendar so nothing slips through.',
    whoCanUse: 'all',
    mainActions: ['Browse deadlines by month', 'Navigate to grant detail from calendar event'],
    relatedFeatures: ['Dashboard', 'GrantDeadline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Help',
    route: '/Help',
    navGroup: 'help',
    title: 'Help Center',
    description: 'Guides, FAQs, and documentation to help you get the most out of GrantFlow.',
    purpose: 'Find answers to common questions, understand each feature, and get step-by-step guidance.',
    whoCanUse: 'all',
    mainActions: ['Search help topics', 'Browse FAQs', 'Contact support'],
    relatedFeatures: ['Dashboard'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'MyProfiles',
    route: '/MyProfiles',
    navGroup: 'setup',
    title: 'My Profiles',
    description: 'Manage your organization profiles — the entities you apply for grants as.',
    purpose: 'Profiles store all the information GrantFlow uses to match you to funding opportunities. Each profile represents a distinct applicant (individual, nonprofit, business, etc.).',
    whoCanUse: 'all',
    mainActions: ['Create a new profile', 'Edit existing profiles', 'Switch active profile', 'Complete profile sections for better matches'],
    relatedFeatures: ['SmartMatcher', 'ProfileMatcher', 'Organizations'],
    affectsMatching: true,
    fields: [
      {
        key: 'zip',
        label: 'ZIP Code',
        explanation: 'Your 5-digit US postal code.',
        whyItMatters: 'Determines which local, county, and state funding opportunities appear in your results. Many grants are restricted to specific zip codes or counties.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: true,
        example: '37201',
      },
      {
        key: 'state',
        label: 'State',
        explanation: 'The US state your organization or household is located in.',
        whyItMatters: 'State-specific grants and programs are filtered by this field. Setting it correctly ensures state government and foundation grants appear.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: true,
        example: 'Tennessee',
      },
      {
        key: 'entity_type',
        label: 'Entity / Applicant Type',
        explanation: 'Whether you are applying as an individual, nonprofit, small business, government agency, or other entity type.',
        whyItMatters: 'Most grants restrict eligibility to specific entity types. This is the primary filter for match eligibility.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: true,
        example: 'nonprofit',
      },
      {
        key: 'naics_codes',
        label: 'NAICS Industry Codes',
        explanation: 'North American Industry Classification System codes describing your industry sector.',
        whyItMatters: 'Industry-specific grants, SBA programs, and federal opportunities filter by NAICS code. Adding accurate codes unlocks sector-specific funding.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: '541611 (Management Consulting)',
      },
      {
        key: 'revenue',
        label: 'Annual Revenue',
        explanation: "Your organization's or household's approximate annual revenue or income.",
        whyItMatters: 'Income thresholds determine eligibility for many need-based grants and programs. Low-income or small-revenue status unlocks additional opportunities.',
        affectsMatching: true,
        affectsCrawlers: false,
        required: false,
        example: '$250,000',
      },
      {
        key: 'health_conditions',
        label: 'Health Conditions',
        explanation: 'Chronic illnesses, disabilities, or medical conditions that apply to you or your household.',
        whyItMatters: 'Health-condition grants, disease-specific foundations, and medical assistance programs match on this data — including the patient and disease-specific copay/assistance foundations GrantFlow now discovers. Required to see medical/disability grants, and used to match recruiting clinical trials if you turn that option on.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'Type 2 Diabetes, Hearing Impairment',
      },
      {
        key: 'clinical_trials_opt_in',
        label: 'Show Recruiting Clinical Trials (opt-in)',
        explanation: 'An optional toggle on the Health tab. When you turn it on, GrantFlow shows currently-recruiting clinical trials and research studies — including early-stage and Phase 1 — that match your medical conditions, each with its official ClinicalTrials.gov link. It is OFF by default and is entirely your choice.',
        whyItMatters: 'A clinical trial is a study, NOT funding. GrantFlow only surfaces the listing so you can decide for yourself: it never enrolls you, never submits anything on your behalf, and never shares your medical information with researchers. You sign up directly on ClinicalTrials.gov or by contacting the study team. Turning this on does not affect your grant matches.',
        affectsMatching: false,
        affectsCrawlers: true,
        required: false,
        example: 'On (you have opted in to see recruiting studies)',
      },
      {
        key: 'financial_details',
        label: 'Financial Details',
        explanation: 'Household income, assets, poverty level status, and other financial indicators.',
        whyItMatters: 'Need-based grants, utility assistance, housing programs, and emergency funds filter heavily on financial data.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'Below 200% federal poverty level',
      },
      {
        key: 'education',
        label: 'Education Level',
        explanation: 'Your highest level of educational attainment.',
        whyItMatters: 'Education grants, scholarships, and workforce development programs filter by education level.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'High School Diploma / GED',
      },
      {
        key: 'military_status',
        label: 'Military / Veteran Status',
        explanation: 'Whether you or someone in your household is an active military member, veteran, or military dependent.',
        whyItMatters: 'Veteran-specific grants, VA programs, and military family benefits require this flag to surface.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'Veteran (Army, honorable discharge)',
      },
      {
        key: 'government_assistance',
        label: 'Government Assistance Programs',
        explanation: 'Any government programs you currently receive (SNAP, Medicaid, WIC, SSI, etc.).',
        whyItMatters: 'Many supplemental programs require or prefer applicants already enrolled in base programs. This unlocks categorical eligibility pathways.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'SNAP, Medicaid',
      },
      {
        key: 'family_composition',
        label: 'Family Composition',
        explanation: 'Household size, presence of children, elderly members, or individuals with disabilities.',
        whyItMatters: 'Family-specific grants, childcare assistance, elder care programs, and per-capita income calculations depend on household composition.',
        affectsMatching: true,
        affectsCrawlers: true,
        required: false,
        example: 'Single parent, 2 children under 12',
      },
    ],
  },
  {
    key: 'Organizations',
    route: '/Organizations',
    navGroup: 'setup',
    title: 'Organizations',
    description: 'View and manage organizations linked to your account.',
    purpose: 'Organizations are the top-level legal entities. Profiles belong to organizations. Manage tax IDs, addresses, and org-level details here.',
    whoCanUse: 'all',
    mainActions: ['Create a new organization', 'Edit organization details', 'Link profiles to an organization'],
    relatedFeatures: ['MyProfiles'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Settings',
    route: '/Settings',
    navGroup: 'setup',
    title: 'Settings',
    description: 'Account preferences, notifications, and general app settings.',
    purpose: 'Customise your GrantFlow experience: notification preferences, theme, email, and security settings.',
    whoCanUse: 'all',
    mainActions: ['Update email or password', 'Set notification preferences', 'Change display preferences'],
    relatedFeatures: ['MyProfiles'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'DiscoverGrants',
    route: '/DiscoverGrants',
    navGroup: 'find',
    title: 'Discover Grants',
    description: 'Find funding sources for your active profile. One click searches live and fires every crawler that fits your profile.',
    purpose:
      'When you click "Find funding sources", GrantFlow does two things at once for your active profile. (1) It searches LIVE right now across federal connectors — Grants.gov, SAM.gov / federal assistance listings (CFDA, including FEMA and CDC programs), NIH, USASpending, and ProPublica nonprofit foundations — plus the curated GrantFlow catalog, so results start appearing immediately. (2) It dispatches, in the background, only the crawlers that are RELEVANT to your profile type, and more matches appear as those finish. Relevance is gated by profile type: a corporation or nonprofit gets foundation and corporate-grant crawlers but NOT student-scholarship or school-endowment crawlers; a student gets scholarship, student-grant and bridge-funding crawlers but NOT veteran-only or fire-department crawlers; clinical-trial discovery only runs if you opted in on the Health tab. Two rules always apply to what you see: the match-percentage slider is a HARD floor — set it to 80% and nothing below 80% is shown — and anything already in this profile\'s pipeline (saved or dismissed) is never shown again. GrantFlow surfaces opportunities and explains the fit; it never guarantees funding and never applies for you without your go-ahead.',
    whoCanUse: 'all',
    mainActions: [
      'Click "Find funding sources" to search live and fire all relevant crawlers',
      'Drag the match-percentage slider to set a hard minimum (e.g. 80% hides everything below 80%)',
      'Add opportunities to your pipeline (saved/dismissed items are never re-shown)',
      'Watch for new matches as background crawlers finish',
    ],
    relatedFeatures: ['FundingResults', 'SmartMatcher', 'DataSources', 'MyProfiles'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'FundingResults',
    route: '/FundingResults',
    navGroup: 'find',
    title: 'Funding Results',
    description: 'Browse all funding opportunities in one place. Filter and sort.',
    purpose:
      'Review all crawled and matched funding results for your active profile. Two rules shape the list: the match-percentage slider is a HARD floor (set it to 80% and nothing scored below 80% appears — it is filtered out, not just sorted down), and anything already in this profile\'s pipeline (saved or dismissed) is never shown again. Results include the newer funding categories GrantFlow now discovers — corporate matching-gift and corporate-foundation grants for nonprofits, re-entry / justice-involved funding, patient and disease-specific copay and assistance foundations, and school endowments — alongside the existing federal, state, foundation and scholarship sources. Apply advanced filters to narrow to your best-fit opportunities.',
    whoCanUse: 'all',
    mainActions: ['Set the match-% slider as a hard minimum', 'Filter by score, type, deadline', 'Sort by relevance or deadline', 'Add to pipeline'],
    relatedFeatures: ['DiscoverGrants', 'SmartMatcher', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'SmartMatcher',
    route: '/SmartMatcher',
    navGroup: 'find',
    title: 'Smart Matcher',
    description:
      'Find grants that fit your profile automatically, with plain-language explanations for every result. You can also type what you need in your own words and use Understand & search.',
    purpose:
      'GrantFlow uses a single matching engine (matchEngine.js v3.0.0) that scores each opportunity 0-100 based on: geographic match (state/county/city/ZIP), applicant type match, keyword overlap, category alignment, and eligibility checks. Every result includes a reasons[] array explaining why it matched. The canonical decision engine assigns ACCEPT (score ≥ 60), REVIEW (30-59), or REJECT (< 30 or hard ineligible). The Describe what you need area plus Understand & search expands plain language into several catalog search terms (OR-style) so related programs are not missed. The more complete your profile, the better the matches.', // Keep version in sync with MATCHER_VERSION in matchEngine.js
    whoCanUse: 'all',
    mainActions: [
      'Describe your need in plain language (Understand & search)',
      'Run Smart Match for active profile',
      'View match scores and explanations',
      'Add top matches to pipeline',
    ],
    relatedFeatures: ['ProfileMatcher', 'FundingResults', 'MyProfiles'],
    affectsMatching: true,
    fields: [],
  },
  {
    key: 'ProfileMatcher',
    route: '/ProfileMatcher',
    navGroup: 'find',
    title: 'Profile Matcher',
    description: 'See exactly how your profile scores against a specific opportunity and what would improve your fit.',
    purpose: "Deep-dive into how a specific profile matches against a specific opportunity. The matching engine checks geographic fit, applicant type, keyword overlap, category alignment, and eligibility — then shows you a score and plain-language reasons. Use this to understand why you do or don't qualify and what profile changes would improve your score.",
    whoCanUse: 'all',
    mainActions: ['Select a profile and an opportunity', 'View detailed eligibility breakdown', 'Identify profile gaps'],
    relatedFeatures: ['SmartMatcher', 'MyProfiles'],
    affectsMatching: true,
    fields: [],
  },
  {
    key: 'FundingOpportunities',
    route: '/FundingOpportunities',
    navGroup: 'find',
    title: 'Funding Opportunities',
    description: 'Browse all funding opportunities from every source in one searchable list.',
    purpose: 'Comprehensive catalogue of all funding opportunities across all sources.',
    whoCanUse: 'all',
    mainActions: ['Browse catalogue', 'Filter by type, source, or amount', 'View opportunity details'],
    relatedFeatures: ['DataSources', 'DiscoverGrants'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Funder',
    route: '/Funder',
    navGroup: 'find',
    title: 'Funder',
    description: 'Explore funders and their grant programs.',
    purpose: 'Research funding organisations — foundations, government agencies, and corporations — and understand their focus areas and giving history.',
    whoCanUse: 'all',
    mainActions: ["Browse funders by type or focus", "View a funder's active programs", 'Add funder opportunities to pipeline'],
    relatedFeatures: ['FundingOpportunities', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'DataSources',
    route: '/DataSources',
    navGroup: 'find',
    title: 'Data Sources',
    description: 'Manage external data sources that feed grant information into GrantFlow.',
    purpose: 'View and manage which data sources are active, when they were last crawled, and their status.',
    whoCanUse: 'all',
    mainActions: ['View source status', 'Trigger source refresh', 'Add new data source'],
    relatedFeatures: ['SourceDirectory', 'DiscoverGrants'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'SourceDirectory',
    route: '/SourceDirectory',
    navGroup: 'find',
    title: 'Source Directory',
    description: 'Browse the directory of funding sources and APIs.',
    purpose: 'A curated directory of all known funding sources — government portals, foundations, and aggregators.',
    whoCanUse: 'all',
    mainActions: ['Browse source directory', 'View source details', 'Enable a source'],
    relatedFeatures: ['DataSources'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'NOFOParser',
    route: '/NOFOParser',
    navGroup: 'find',
    title: 'NOFO Parser',
    description: 'Parse Notice of Funding Opportunity (NOFO) documents for structured data.',
    purpose: 'Upload or paste a NOFO document and let AI extract key details: eligibility, deadlines, funding amounts, requirements, and application instructions.',
    whoCanUse: 'advanced',
    mainActions: ['Upload a NOFO PDF or paste text', 'Extract structured grant data', 'Add parsed opportunity to pipeline'],
    relatedFeatures: ['AIGrantScorer', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'AIGrantScorer',
    route: '/AIGrantScorer',
    navGroup: 'find',
    title: 'AI Grant Scorer',
    description: 'Score grants with AI to prioritise which to pursue.',
    purpose: 'Use AI to rapidly evaluate a list of opportunities and rank them by likelihood of success given your profile and capacity.',
    whoCanUse: 'advanced',
    mainActions: ['Upload grant list or paste descriptions', 'Get AI-generated priority scores', 'Export ranked list'],
    relatedFeatures: ['NOFOParser', 'SmartMatcher'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Pipeline',
    route: '/Pipeline',
    navGroup: 'work',
    title: 'Pipeline',
    description: "Your grant pipeline: track applications from discovery to submission.",
    purpose: "Manage every grant opportunity you're actively pursuing. Move them through stages: Discovered → Interested → Drafting → Submitted → Won/Lost.",
    whoCanUse: 'all',
    mainActions: ['Add opportunities to pipeline', 'Update application stage', 'View upcoming deadlines', 'Track submission history'],
    relatedFeatures: ['Proposals', 'Documents', 'GrantDeadline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Proposals',
    route: '/Proposals',
    navGroup: 'work',
    title: 'Proposals',
    description: 'Manage proposals and application drafts.',
    purpose: 'Create and manage grant proposal documents, draft narratives, budgets, and letters of intent.',
    whoCanUse: 'all',
    mainActions: ['Create a new proposal', 'Draft needs statement or narrative', 'Link proposal to pipeline item'],
    relatedFeatures: ['Pipeline', 'Documents'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Documents',
    route: '/Documents',
    navGroup: 'work',
    title: 'Documents',
    description: 'Upload, store, and organise application documents.',
    purpose: 'Central document repository for all grant-related files: financial statements, letters of support, IRS determination letters, and other attachments.',
    whoCanUse: 'all',
    mainActions: ['Upload documents', 'Organise by tag or pipeline item', 'Share or download files'],
    relatedFeatures: ['Proposals', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'PrintableApplication',
    route: '/PrintableApplication',
    navGroup: 'work',
    title: 'Printable Application',
    description: 'Generate a printable version of an application for offline work.',
    purpose: 'Create a print-ready PDF or formatted document combining all application components.',
    whoCanUse: 'all',
    mainActions: ['Select pipeline item', 'Generate printable packet', 'Download or print PDF'],
    relatedFeatures: ['Proposals', 'Documents'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'GrantDeadline',
    route: '/GrantDeadline',
    navGroup: 'track',
    title: 'Grant Deadline',
    description: 'Track upcoming grant deadlines so you never miss one.',
    purpose: 'A focused view of all approaching deadlines across your pipeline. Shows days remaining and priority level.',
    whoCanUse: 'all',
    mainActions: ['View deadline list sorted by urgency', 'Set deadline reminders', 'Link deadline to pipeline item'],
    relatedFeatures: ['Calendar', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'GrantMonitoring',
    route: '/GrantMonitoring',
    navGroup: 'track',
    title: 'Grant Monitoring',
    description: 'Monitor grant status and follow up on submissions.',
    purpose: 'Track the status of submitted applications, log funder communications, and manage post-award reporting requirements.',
    whoCanUse: 'all',
    mainActions: ['Update grant status', 'Log funder contact', 'Set follow-up reminders'],
    relatedFeatures: ['Pipeline', 'Stewardship'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Reports',
    route: '/Reports',
    navGroup: 'track',
    title: 'Reports & Analytics',
    description: 'Reports and analytics on your grant activity.',
    purpose: 'Generate summary reports on grant applications, success rates, funding received, and pipeline health.',
    whoCanUse: 'all',
    mainActions: ['Generate activity report', 'View success rate metrics', 'Export data'],
    relatedFeatures: ['AdvancedAnalytics', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'AdvancedAnalytics',
    route: '/AdvancedAnalytics',
    navGroup: 'track',
    title: 'Advanced Analytics',
    description: 'Deep-dive analytics and visualisations for power users.',
    purpose: 'Interactive charts and trend analysis of your grant outcomes, match quality over time, and funding pipeline performance.',
    whoCanUse: 'advanced',
    mainActions: ['Explore match score trends', 'Analyse pipeline velocity', 'Compare periods'],
    relatedFeatures: ['Reports'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Outreach',
    route: '/Outreach',
    navGroup: 'track',
    title: 'Outreach',
    description: 'Manage outreach to funders and partners.',
    purpose: 'Log and track all funder communications — emails, calls, meetings — linked to specific grant opportunities.',
    whoCanUse: 'all',
    mainActions: ['Log a funder contact', 'View outreach history', 'Schedule follow-ups'],
    relatedFeatures: ['Pipeline', 'Stewardship'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Stewardship',
    route: '/Stewardship',
    navGroup: 'track',
    title: 'Stewardship',
    description: 'Track stewardship activities and donor relationships.',
    purpose: 'Manage post-award grant compliance, reporting milestones, and relationship maintenance with funders who have awarded grants.',
    whoCanUse: 'all',
    mainActions: ['Log stewardship activity', 'Track report due dates', 'Record grant outcomes'],
    relatedFeatures: ['GrantMonitoring', 'Outreach'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Automation',
    route: '/Automation',
    navGroup: 'admin',
    title: 'Automation',
    description: 'Configure automated workflows and crawler schedules. Robert, the funding-discovery agent, works here in the background.',
    purpose:
      'Set up recurring crawl schedules, automated grant matching triggers, and workflow automations that run in the background. Robert (the funding-discovery agent) runs here automatically: he mines the funding opportunities already in the GrantFlow catalog against each profile and reads funding leads that have been emailed in, then queues the strongest matches as recommendations for you to accept or reject. Robert works only from the existing catalog and emailed leads — he does NOT crawl the open web or search engines for new leads; that is not his job. Recommendations are suggestions you approve, never auto-added applications, and never a guarantee of funding.',
    whoCanUse: 'all',
    mainActions: ['Schedule crawler runs', 'Configure automation triggers', 'Review and accept or reject Robert\'s funding recommendations', 'View automation logs'],
    relatedFeatures: ['DataSources', 'DiscoverGrants', 'Pipeline'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Billing',
    route: '/Billing',
    navGroup: 'admin',
    title: 'Billing & Invoicing',
    description: 'Billing, invoicing, and subscription management.',
    purpose: 'Manage your GrantFlow subscription, view invoices, update payment methods, and track usage.',
    whoCanUse: 'all',
    mainActions: ['View subscription plan', 'Download invoices', 'Update payment method'],
    relatedFeatures: ['Settings'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Budgets',
    route: '/Budgets',
    navGroup: 'admin',
    title: 'Budgets',
    description: 'Manage budgets and expense tracking for grants.',
    purpose: 'Create and track grant budgets, monitor spend against awards, and generate budget reports for compliance.',
    whoCanUse: 'all',
    mainActions: ['Create a budget', 'Track expenses against budget', 'Generate budget report'],
    relatedFeatures: ['Pipeline', 'Reports'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Diagnostics',
    route: '/Diagnostics',
    navGroup: 'admin',
    title: 'Diagnostics',
    description: 'System diagnostics and troubleshooting tools.',
    purpose: 'View system health, check crawler status, inspect database statistics, and diagnose issues with the GrantFlow platform.',
    whoCanUse: 'all',
    mainActions: ['View system health', 'Check crawler job queue', 'Inspect database stats'],
    relatedFeatures: ['DataSources', 'Automation'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Admin',
    route: '/Admin',
    navGroup: 'admin',
    title: 'Admin Panel',
    description: 'Admin panel for system configuration and user management.',
    purpose: 'Full system administration: manage users, profiles, organizations, API keys, crawler configuration, and system-wide settings.',
    whoCanUse: 'admin',
    mainActions: ['Manage users and roles', 'Configure system settings', 'View audit logs', 'Manage API keys'],
    relatedFeatures: ['Diagnostics', 'Automation'],
    affectsMatching: false,
    fields: [],
  },
  {
    key: 'Incognito',
    route: '/Incognito',
    navGroup: 'admin',
    title: 'Incognito',
    description: 'Privacy mode: remove sensitive data before sharing screenshots or exports.',
    purpose: 'Temporarily mask sensitive profile data (names, addresses, financial figures) when sharing your screen or exporting reports.',
    whoCanUse: 'privacy',
    mainActions: ['Enable incognito mask', 'Adjust which fields are masked', 'Export masked report'],
    relatedFeatures: ['Settings'],
    affectsMatching: false,
    fields: [],
  },
]

// ── Helper functions ──────────────────────────────────────────────────────────

/**
 * Look up a registry entry by routeName key.
 * @param {string} routeName
 * @returns {object|undefined}
 */
export function getHelpForRoute(routeName) {
  return HELP_REGISTRY.find((entry) => entry.key === routeName)
}

/**
 * Look up a field definition by its key across all registry entries.
 * @param {string} fieldKey
 * @returns {{ field: object, page: object }|undefined}
 */
export function getHelpForField(fieldKey) {
  for (const entry of HELP_REGISTRY) {
    const field = entry.fields?.find((f) => f.key === fieldKey)
    if (field) return { field, page: entry }
  }
  return undefined
}

/**
 * Full-text search across the help registry.
 * @param {string} query
 * @returns {Array<object>}
 */
export function searchHelp(query) {
  if (!query || !query.trim()) return HELP_REGISTRY
  const q = query.trim().toLowerCase()
  return HELP_REGISTRY.filter((entry) => {
    const searchableText = [
      entry.title,
      entry.description,
      entry.purpose,
      ...(entry.mainActions ?? []),
      entry.navGroup,
      ...(entry.fields ?? []).flatMap((f) => [f.label, f.explanation, f.whyItMatters]),
    ]
      .filter(Boolean)
      .join(' ')
      .toLowerCase()
    return searchableText.includes(q)
  })
}

/**
 * Returns a structured JSON summary of the entire app that can be injected
 * into Anya's system prompt.
 * @returns {string} JSON string
 */
export function getAppOverview() {
  const overview = {
    pages: HELP_REGISTRY.map((e) => ({
      key: e.key,
      title: e.title,
      navGroup: e.navGroup,
      description: e.description,
      purpose: e.purpose,
      whoCanUse: e.whoCanUse,
      mainActions: e.mainActions,
      affectsMatching: e.affectsMatching,
      fieldCount: e.fields?.length ?? 0,
    })),
    matchingFields: HELP_REGISTRY.flatMap((e) =>
      (e.fields ?? [])
        .filter((f) => f.affectsMatching)
        .map((f) => ({
          key: f.key,
          label: f.label,
          page: e.key,
          explanation: f.explanation,
          whyItMatters: f.whyItMatters,
          affectsCrawlers: f.affectsCrawlers,
          required: f.required,
        }))
    ),
  }
  return JSON.stringify(overview, null, 2)
}
