/**
 * FUNCTION REGISTRY - Static registry of all backend functions and modules
 * 
 * This file must be manually maintained or generated by a one-time script.
 * It contains metadata about every executable function, helper, and shared module.
 * 
 * PORTABLE: Copy this file to any Base44 app and update the entries.
 */

export const KNOWN_FUNCTIONS = [
  // ============================================
  // ANALYSIS FUNCTIONS
  // ============================================
  {
    functionId: 'analyzeGrant',
    filePath: 'functions/analyzeGrant.js',
    exportType: 'default',
    namedExports: [],
    category: 'analysis',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js',
      'functions/_shared/safeHandler.js'
    ]
  },
  {
    functionId: 'analyze2grant',
    filePath: 'functions/analyze2grant.js',
    exportType: 'default',
    namedExports: [],
    category: 'analysis',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js'
    ]
  },
  {
    functionId: 'analyzeProposal',
    filePath: 'functions/analyzeProposal.js',
    exportType: 'default',
    namedExports: [],
    category: 'analysis',
    dependencyPaths: []
  },
  {
    functionId: 'analyzeProjectOutcomes',
    filePath: 'functions/analyzeProjectOutcomes.js',
    exportType: 'default',
    namedExports: [],
    category: 'analysis',
    dependencyPaths: []
  },
  {
    functionId: 'analyzeTaxSituation',
    filePath: 'functions/analyzeTaxSituation.js',
    exportType: 'default',
    namedExports: [],
    category: 'analysis',
    dependencyPaths: []
  },

  // ============================================
  // MATCHING FUNCTIONS
  // ============================================
  {
    functionId: 'aiGrantMatcher',
    filePath: 'functions/aiGrantMatcher.js',
    exportType: 'default',
    namedExports: [],
    category: 'matching',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js',
      'functions/_shared/cosineSimilarity.js'
    ]
  },
  {
    functionId: 'comprehensiveMatch',
    filePath: 'functions/comprehensiveMatch.js',
    exportType: 'default',
    namedExports: [],
    category: 'matching',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js'
    ]
  },
  {
    functionId: 'matchGrantsForOrganization',
    filePath: 'functions/matchGrantsForOrganization.js',
    exportType: 'default',
    namedExports: [],
    category: 'matching',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/pipelineIsolation.js'
    ]
  },
  {
    functionId: 'matchProfileToGrants',
    filePath: 'functions/matchProfileToGrants.js',
    exportType: 'default',
    namedExports: [],
    category: 'matching',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js'
    ]
  },
  {
    functionId: 'matchFunderToProfile',
    filePath: 'functions/matchFunderToProfile.js',
    exportType: 'default',
    namedExports: [],
    category: 'matching',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },

  // ============================================
  // SEARCH FUNCTIONS
  // ============================================
  {
    functionId: 'searchOpportunities',
    filePath: 'functions/searchOpportunities.js',
    exportType: 'default',
    namedExports: [],
    category: 'search',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'searchForItem',
    filePath: 'functions/searchForItem.js',
    exportType: 'default',
    namedExports: [],
    category: 'search',
    dependencyPaths: []
  },
  {
    functionId: 'searchForSource',
    filePath: 'functions/searchForSource.js',
    exportType: 'default',
    namedExports: [],
    category: 'search',
    dependencyPaths: []
  },
  {
    functionId: 'getSearchJob',
    filePath: 'functions/getSearchJob.js',
    exportType: 'default',
    namedExports: [],
    category: 'search',
    dependencyPaths: []
  },

  // ============================================
  // DISCOVERY FUNCTIONS
  // ============================================
  {
    functionId: 'discoverLocalSources',
    filePath: 'functions/discoverLocalSources.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: [
      'functions/_shared/saveFundingSource.js',
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'discoverStudentSources',
    filePath: 'functions/discoverStudentSources.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: [
      'functions/_shared/saveFundingSource.js',
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'discoverECFSources',
    filePath: 'functions/discoverECFSources.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: [
      'functions/_shared/saveFundingSource.js'
    ]
  },
  {
    functionId: 'discoverECFServices',
    filePath: 'functions/discoverECFServices.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: []
  },
  {
    functionId: 'autoDiscoverSources',
    filePath: 'functions/autoDiscoverSources.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: [
      'functions/_shared/saveFundingSource.js',
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'runAutomatedDiscovery',
    filePath: 'functions/runAutomatedDiscovery.js',
    exportType: 'default',
    namedExports: [],
    category: 'discovery',
    dependencyPaths: [
      'functions/_shared/atomicLock.js'
    ]
  },

  // ============================================
  // CRAWLER FUNCTIONS
  // ============================================
  {
    functionId: 'crawlGrantsGov',
    filePath: 'functions/crawlGrantsGov.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js',
      'functions/_shared/crawlerStability.js'
    ]
  },
  {
    functionId: 'crawlBenefitsGov',
    filePath: 'functions/crawlBenefitsGov.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlECFChoices',
    filePath: 'functions/crawlECFChoices.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlWebsite',
    filePath: 'functions/crawlWebsite.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlSourceDirectory',
    filePath: 'functions/crawlSourceDirectory.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlDSIRE',
    filePath: 'functions/crawlDSIRE.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlIrs990',
    filePath: 'functions/crawlIrs990.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlLeeUniversity',
    filePath: 'functions/crawlLeeUniversity.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlUniversityScholarships',
    filePath: 'functions/crawlUniversityScholarships.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'crawlCLSFM',
    filePath: 'functions/crawlCLSFM.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: [
      'functions/_shared/crawlerFramework.js'
    ]
  },
  {
    functionId: 'scheduledCrawl',
    filePath: 'functions/scheduledCrawl.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: []
  },
  {
    functionId: 'queueCrawl',
    filePath: 'functions/queueCrawl.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: []
  },
  {
    functionId: 'runPartnerFeed',
    filePath: 'functions/runPartnerFeed.js',
    exportType: 'default',
    namedExports: [],
    category: 'crawlers',
    dependencyPaths: []
  },

  // ============================================
  // PROCESSING FUNCTIONS
  // ============================================
  {
    functionId: 'processSingleGrant',
    filePath: 'functions/processSingleGrant.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/profileMatchingEngine.js',
      'functions/_shared/pipelineIsolation.js'
    ]
  },
  {
    functionId: 'processCrawledItem',
    filePath: 'functions/processCrawledItem.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: [
      'functions/_shared/processingQueue.js'
    ]
  },
  {
    functionId: 'processOpportunity',
    filePath: 'functions/processOpportunity.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: []
  },
  {
    functionId: 'processFoundation',
    filePath: 'functions/processFoundation.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: []
  },
  {
    functionId: 'processDocumentForFacts',
    filePath: 'functions/processDocumentForFacts.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: [
      'functions/_shared/phiAuditLogger.js'
    ]
  },
  {
    functionId: 'processScannedApplication',
    filePath: 'functions/processScannedApplication.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: []
  },
  {
    functionId: 'processApplicationEmail',
    filePath: 'functions/processApplicationEmail.js',
    exportType: 'default',
    namedExports: [],
    category: 'processing',
    dependencyPaths: []
  },

  // ============================================
  // AUTOMATION FUNCTIONS
  // ============================================
  {
    functionId: 'backgroundWorker',
    filePath: 'functions/backgroundWorker.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/atomicLock.js',
      'functions/_shared/processingQueue.js'
    ]
  },
  {
    functionId: 'autoMonitor',
    filePath: 'functions/autoMonitor.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/atomicLock.js'
    ]
  },
  {
    functionId: 'runBatchAutomation',
    filePath: 'functions/runBatchAutomation.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/atomicLock.js',
      'functions/_shared/processingQueue.js'
    ]
  },
  {
    functionId: 'runSmartAutomation',
    filePath: 'functions/runSmartAutomation.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/atomicLock.js'
    ]
  },
  {
    functionId: 'runBackgroundAutoAdvance',
    filePath: 'functions/runBackgroundAutoAdvance.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/atomicLock.js',
      'functions/_shared/pipelineIsolation.js'
    ]
  },
  {
    functionId: 'enqueueGrant',
    filePath: 'functions/enqueueGrant.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: [
      'functions/_shared/processingQueue.js'
    ]
  },
  {
    functionId: 'getBackgroundJobStatus',
    filePath: 'functions/getBackgroundJobStatus.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: []
  },
  {
    functionId: 'runVerification',
    filePath: 'functions/runVerification.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: []
  },
  {
    functionId: 'runGrantBackfill',
    filePath: 'functions/runGrantBackfill.js',
    exportType: 'default',
    namedExports: [],
    category: 'automation',
    dependencyPaths: []
  },

  // ============================================
  // EMAIL FUNCTIONS
  // ============================================
  {
    functionId: 'sendEmailResend',
    filePath: 'functions/sendEmailResend.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },
  {
    functionId: 'sendInvoice',
    filePath: 'functions/sendInvoice.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },
  {
    functionId: 'sendDeadlineAlerts',
    filePath: 'functions/sendDeadlineAlerts.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },
  {
    functionId: 'sendReportReminders',
    filePath: 'functions/sendReportReminders.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },
  {
    functionId: 'notifyAdminNewMessage',
    filePath: 'functions/notifyAdminNewMessage.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },
  {
    functionId: 'notifyAdminNewUser',
    filePath: 'functions/notifyAdminNewUser.js',
    exportType: 'default',
    namedExports: [],
    category: 'email',
    dependencyPaths: []
  },

  // ============================================
  // GENERATION FUNCTIONS
  // ============================================
  {
    functionId: 'generateProposalSection',
    filePath: 'functions/generateProposalSection.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'generateGrantProposal',
    filePath: 'functions/generateGrantProposal.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'generateApplicationResponse',
    filePath: 'functions/generateApplicationResponse.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'generateProgressReport',
    filePath: 'functions/generateProgressReport.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: []
  },
  {
    functionId: 'generateReport',
    filePath: 'functions/generateReport.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: []
  },
  {
    functionId: 'generateOutreachMessage',
    filePath: 'functions/generateOutreachMessage.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: []
  },
  {
    functionId: 'autoGenerateBulkOutreach',
    filePath: 'functions/autoGenerateBulkOutreach.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: []
  },
  {
    functionId: 'generateTaxReturn',
    filePath: 'functions/generateTaxReturn.js',
    exportType: 'default',
    namedExports: [],
    category: 'generation',
    dependencyPaths: []
  },

  // ============================================
  // REFINEMENT FUNCTIONS
  // ============================================
  {
    functionId: 'refineGrantText',
    filePath: 'functions/refineGrantText.js',
    exportType: 'default',
    namedExports: [],
    category: 'refinement',
    dependencyPaths: []
  },
  {
    functionId: 'refineProposalText',
    filePath: 'functions/refineProposalText.js',
    exportType: 'default',
    namedExports: [],
    category: 'refinement',
    dependencyPaths: []
  },

  // ============================================
  // SUGGESTION FUNCTIONS
  // ============================================
  {
    functionId: 'getAIRecommendations',
    filePath: 'functions/getAIRecommendations.js',
    exportType: 'default',
    namedExports: [],
    category: 'suggestions',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },
  {
    functionId: 'getSuggestedEnhancements',
    filePath: 'functions/getSuggestedEnhancements.js',
    exportType: 'default',
    namedExports: [],
    category: 'suggestions',
    dependencyPaths: []
  },
  {
    functionId: 'suggestGrantKeywords',
    filePath: 'functions/suggestGrantKeywords.js',
    exportType: 'default',
    namedExports: [],
    category: 'suggestions',
    dependencyPaths: []
  },
  {
    functionId: 'suggestProposalKeywords',
    filePath: 'functions/suggestProposalKeywords.js',
    exportType: 'default',
    namedExports: [],
    category: 'suggestions',
    dependencyPaths: []
  },
  {
    functionId: 'suggestDocumentsForGrant',
    filePath: 'functions/suggestDocumentsForGrant.js',
    exportType: 'default',
    namedExports: [],
    category: 'suggestions',
    dependencyPaths: []
  },

  // ============================================
  // VALIDATION FUNCTIONS
  // ============================================
  {
    functionId: 'checkApplicationAvailability',
    filePath: 'functions/checkApplicationAvailability.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: []
  },
  {
    functionId: 'checkApplicationCompliance',
    filePath: 'functions/checkApplicationCompliance.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: []
  },
  {
    functionId: 'checkGrantAlerts',
    filePath: 'functions/checkGrantAlerts.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: []
  },
  {
    functionId: 'checkPendingApplications',
    filePath: 'functions/checkPendingApplications.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: []
  },
  {
    functionId: 'validatePipelineAdvancement',
    filePath: 'functions/validatePipelineAdvancement.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: [
      'functions/_shared/pipelineIsolation.js'
    ]
  },
  {
    functionId: 'verifyProfileIsolation',
    filePath: 'functions/verifyProfileIsolation.js',
    exportType: 'default',
    namedExports: [],
    category: 'validation',
    dependencyPaths: [
      'functions/_shared/profileIsolation.js',
      'functions/_shared/strictProfileValidator.js'
    ]
  },

  // ============================================
  // PARSING FUNCTIONS
  // ============================================
  {
    functionId: 'parseNOFO',
    filePath: 'functions/parseNOFO.js',
    exportType: 'default',
    namedExports: [],
    category: 'parsing',
    dependencyPaths: []
  },
  {
    functionId: 'parseFunderWebsite',
    filePath: 'functions/parseFunderWebsite.js',
    exportType: 'default',
    namedExports: [],
    category: 'parsing',
    dependencyPaths: []
  },

  // ============================================
  // ADMIN FUNCTIONS
  // ============================================
  {
    functionId: 'getUserList',
    filePath: 'functions/getUserList.js',
    exportType: 'default',
    namedExports: [],
    category: 'admin',
    dependencyPaths: [
      'functions/_shared/adminGuard.js'
    ]
  },
  {
    functionId: 'deleteUser',
    filePath: 'functions/deleteUser.js',
    exportType: 'default',
    namedExports: [],
    category: 'admin',
    dependencyPaths: [
      'functions/_shared/adminGuard.js'
    ]
  },
  {
    functionId: 'deleteOrganizationWithCascade',
    filePath: 'functions/deleteOrganizationWithCascade.js',
    exportType: 'default',
    namedExports: [],
    category: 'admin',
    dependencyPaths: [
      'functions/_shared/adminGuard.js'
    ]
  },
  {
    functionId: 'deleteSourceWithCascade',
    filePath: 'functions/deleteSourceWithCascade.js',
    exportType: 'default',
    namedExports: [],
    category: 'admin',
    dependencyPaths: [
      'functions/_shared/adminGuard.js'
    ]
  },

  // ============================================
  // SUBMISSION FUNCTIONS
  // ============================================
  {
    functionId: 'submitGrant',
    filePath: 'functions/submitGrant.js',
    exportType: 'default',
    namedExports: [],
    category: 'submission',
    dependencyPaths: []
  },
  {
    functionId: 'submitPublicApplication',
    filePath: 'functions/submitPublicApplication.js',
    exportType: 'default',
    namedExports: [],
    category: 'submission',
    dependencyPaths: []
  },
  {
    functionId: 'prepareGrantSubmission',
    filePath: 'functions/prepareGrantSubmission.js',
    exportType: 'default',
    namedExports: [],
    category: 'submission',
    dependencyPaths: []
  },
  {
    functionId: 'autoFillApplicationForm',
    filePath: 'functions/autoFillApplicationForm.js',
    exportType: 'default',
    namedExports: [],
    category: 'submission',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js'
    ]
  },

  // ============================================
  // PROFILE FUNCTIONS
  // ============================================
  {
    functionId: 'enrichProfileForSearch',
    filePath: 'functions/enrichProfileForSearch.js',
    exportType: 'default',
    namedExports: [],
    category: 'profile',
    dependencyPaths: [
      'functions/_shared/buildNormalizedProfile.js',
      'functions/_shared/parseProfileNarratives.js'
    ]
  },

  // ============================================
  // TAX FUNCTIONS
  // ============================================
  {
    functionId: 'requestTaxDocuments',
    filePath: 'functions/requestTaxDocuments.js',
    exportType: 'default',
    namedExports: [],
    category: 'tax',
    dependencyPaths: []
  },
  {
    functionId: 'exportForTaxSoftware',
    filePath: 'functions/exportForTaxSoftware.js',
    exportType: 'default',
    namedExports: [],
    category: 'tax',
    dependencyPaths: []
  },

  // ============================================
  // CRM FUNCTIONS
  // ============================================
  {
    functionId: 'autoCreateLead',
    filePath: 'functions/autoCreateLead.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'getLeads',
    filePath: 'functions/getLeads.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'getLead',
    filePath: 'functions/getLead.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'createLead',
    filePath: 'functions/createLead.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'updateLead',
    filePath: 'functions/updateLead.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'deleteLead',
    filePath: 'functions/deleteLead.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'getActivities',
    filePath: 'functions/getActivities.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },
  {
    functionId: 'getLeadActivities',
    filePath: 'functions/getLeadActivities.js',
    exportType: 'default',
    namedExports: [],
    category: 'crm',
    dependencyPaths: []
  },

  // ============================================
  // PUBLIC FUNCTIONS
  // ============================================
  {
    functionId: 'publicApplicationForm',
    filePath: 'functions/publicApplicationForm.js',
    exportType: 'default',
    namedExports: [],
    category: 'public',
    dependencyPaths: []
  },

  // ============================================
  // DEBUG FUNCTIONS
  // ============================================
  {
    functionId: 'simulatePipelineRunDebug',
    filePath: 'functions/simulatePipelineRunDebug.js',
    exportType: 'default',
    namedExports: [],
    category: 'debug',
    dependencyPaths: [
      'functions/_shared/pipelineIsolation.js'
    ]
  },

  // ============================================
  // SYSTEM/META FUNCTIONS
  // ============================================
  {
    functionId: 'findAllFunctions',
    filePath: 'functions/findAllFunctions.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'findAllFunctionsHybrid',
    filePath: 'functions/findAllFunctionsHybrid.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'testAllFunctions',
    filePath: 'functions/testAllFunctions.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'testSharedModules',
    filePath: 'functions/testSharedModules.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'autoGenerateFunctionTestPayloads',
    filePath: 'functions/autoGenerateFunctionTestPayloads.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'autoGenerateFunctionTestPayloadsHard',
    filePath: 'functions/autoGenerateFunctionTestPayloadsHard.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'writeAllTestPayloadsNow',
    filePath: 'functions/writeAllTestPayloadsNow.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'createPayloadsForAllFunctions',
    filePath: 'functions/createPayloadsForAllFunctions.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'getFunctionCode',
    filePath: 'functions/getFunctionCode.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },
  {
    functionId: 'getFunctionDetails',
    filePath: 'functions/getFunctionDetails.js',
    exportType: 'default',
    namedExports: [],
    category: 'system',
    dependencyPaths: []
  },

  // ============================================
  // SHARED MODULES (sorta functions)
  // ============================================
  {
    functionId: '_shared/buildNormalizedProfile',
    filePath: 'functions/_shared/buildNormalizedProfile.js',
    exportType: 'named',
    namedExports: ['buildNormalizedProfile', 'normalizeProfile'],
    category: 'shared',
    dependencyPaths: [
      'functions/_shared/parseProfileNarratives.js',
      'functions/_shared/redactSensitiveProfileFields.js'
    ]
  },
  {
    functionId: '_shared/profileMatchingEngine',
    filePath: 'functions/_shared/profileMatchingEngine.js',
    exportType: 'named',
    namedExports: ['matchProfile', 'scoreMatch', 'calculateEligibility'],
    category: 'shared',
    dependencyPaths: [
      'functions/_shared/cosineSimilarity.js'
    ]
  },
  {
    functionId: '_shared/profileIsolation',
    filePath: 'functions/_shared/profileIsolation.js',
    exportType: 'named',
    namedExports: ['createProfileContext', 'guardQuery', 'guardResults', 'createIsolatedEntityOperations'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/pipelineIsolation',
    filePath: 'functions/_shared/pipelineIsolation.js',
    exportType: 'named',
    namedExports: ['ensurePipelineIsolation', 'validatePipelineAccess'],
    category: 'shared',
    dependencyPaths: [
      'functions/_shared/profileIsolation.js'
    ]
  },
  {
    functionId: '_shared/strictProfileValidator',
    filePath: 'functions/_shared/strictProfileValidator.js',
    exportType: 'named',
    namedExports: ['validateStrictProfile', 'assertProfileOwnership'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/saveFundingSource',
    filePath: 'functions/_shared/saveFundingSource.js',
    exportType: 'named',
    namedExports: ['saveFundingSource', 'saveFundingSources', 'validateSourceData'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/crawlerFramework',
    filePath: 'functions/_shared/crawlerFramework.js',
    exportType: 'named',
    namedExports: ['createCrawler', 'runCrawler', 'parsePage'],
    category: 'shared',
    dependencyPaths: [
      'functions/_shared/crawlerStability.js'
    ]
  },
  {
    functionId: '_shared/crawlerStability',
    filePath: 'functions/_shared/crawlerStability.js',
    exportType: 'named',
    namedExports: ['withRetry', 'rateLimiter', 'handleCrawlError'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/processingQueue',
    filePath: 'functions/_shared/processingQueue.js',
    exportType: 'named',
    namedExports: ['enqueue', 'dequeue', 'processQueue'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/atomicLock',
    filePath: 'functions/_shared/atomicLock.js',
    exportType: 'named',
    namedExports: ['acquireLock', 'releaseLock', 'withLock'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/cosineSimilarity',
    filePath: 'functions/_shared/cosineSimilarity.js',
    exportType: 'named',
    namedExports: ['cosineSimilarity', 'dotProduct', 'magnitude'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/parseProfileNarratives',
    filePath: 'functions/_shared/parseProfileNarratives.js',
    exportType: 'named',
    namedExports: ['parseNarratives', 'extractKeywords'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/redactSensitiveProfileFields',
    filePath: 'functions/_shared/redactSensitiveProfileFields.js',
    exportType: 'named',
    namedExports: ['redactSensitiveFields', 'SENSITIVE_FIELDS'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/phiAuditLogger',
    filePath: 'functions/_shared/phiAuditLogger.js',
    exportType: 'named',
    namedExports: ['logPHIAccess', 'logPHIModification'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/authGuard',
    filePath: 'functions/_shared/authGuard.js',
    exportType: 'named',
    namedExports: ['requireAuth', 'getAuthenticatedUser'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/adminGuard',
    filePath: 'functions/_shared/adminGuard.js',
    exportType: 'named',
    namedExports: ['requireAdmin', 'isAdmin'],
    category: 'shared',
    dependencyPaths: [
      'functions/_shared/authGuard.js'
    ]
  },
  {
    functionId: '_shared/safeHandler',
    filePath: 'functions/_shared/safeHandler.js',
    exportType: 'named',
    namedExports: ['safeHandler', 'wrapHandler'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/rlsSafeSDK',
    filePath: 'functions/_shared/rlsSafeSDK.js',
    exportType: 'named',
    namedExports: ['createRLSSafeSDK', 'withRLS'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/security',
    filePath: 'functions/_shared/security.js',
    exportType: 'named',
    namedExports: ['sanitizeInput', 'validateInput'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/env',
    filePath: 'functions/_shared/env.js',
    exportType: 'named',
    namedExports: ['getEnv', 'requireEnv'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/safety',
    filePath: 'functions/_shared/safety.js',
    exportType: 'named',
    namedExports: ['safeSerialize', 'safeStringify'],
    category: 'shared',
    dependencyPaths: []
  },
  {
    functionId: '_shared/profileSignature',
    filePath: 'functions/_shared/profileSignature.js',
    exportType: 'named',
    namedExports: ['generateProfileSignature', 'compareSignatures'],
    category: 'shared',
    dependencyPaths: []
  }
];

// Category metadata for UI grouping
export const CATEGORIES = {
  analysis: { label: 'Analysis', color: 'blue', icon: 'Brain' },
  matching: { label: 'Matching', color: 'purple', icon: 'Target' },
  search: { label: 'Search', color: 'cyan', icon: 'Search' },
  discovery: { label: 'Discovery', color: 'green', icon: 'Compass' },
  crawlers: { label: 'Crawlers', color: 'orange', icon: 'Globe' },
  processing: { label: 'Processing', color: 'yellow', icon: 'Cog' },
  automation: { label: 'Automation', color: 'red', icon: 'Zap' },
  email: { label: 'Email', color: 'pink', icon: 'Mail' },
  generation: { label: 'Generation', color: 'indigo', icon: 'Sparkles' },
  refinement: { label: 'Refinement', color: 'teal', icon: 'Wand2' },
  suggestions: { label: 'Suggestions', color: 'amber', icon: 'Lightbulb' },
  validation: { label: 'Validation', color: 'lime', icon: 'CheckCircle' },
  parsing: { label: 'Parsing', color: 'sky', icon: 'FileText' },
  admin: { label: 'Admin', color: 'slate', icon: 'Shield' },
  submission: { label: 'Submission', color: 'emerald', icon: 'Send' },
  profile: { label: 'Profile', color: 'violet', icon: 'User' },
  tax: { label: 'Tax', color: 'stone', icon: 'Receipt' },
  crm: { label: 'CRM', color: 'rose', icon: 'Users' },
  public: { label: 'Public', color: 'neutral', icon: 'Globe2' },
  debug: { label: 'Debug', color: 'zinc', icon: 'Bug' },
  system: { label: 'System', color: 'gray', icon: 'Settings' },
  shared: { label: 'Shared Modules', color: 'fuchsia', icon: 'Package' }
};

// Helper to get all unique dependencies across all functions
export function getAllDependencies() {
  const deps = new Set();
  KNOWN_FUNCTIONS.forEach(fn => {
    fn.dependencyPaths?.forEach(dep => deps.add(dep));
  });
  return Array.from(deps);
}

// Helper to find functions by category
export function getFunctionsByCategory(category) {
  return KNOWN_FUNCTIONS.filter(fn => fn.category === category);
}

// Helper to find a function by ID
export function getFunctionById(functionId) {
  return KNOWN_FUNCTIONS.find(fn => fn.functionId === functionId);
}

// Helper to get all categories with counts
export function getCategoryCounts() {
  const counts = {};
  KNOWN_FUNCTIONS.forEach(fn => {
    counts[fn.category] = (counts[fn.category] || 0) + 1;
  });
  return counts;
}