import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, Sparkles, AlertCircle } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useToast } from '@/components/ui/use-toast';

/**
 * GrantNarrativeSection - AI-powered narrative section generator
 * @param {Object} props
 * @param {Object} props.formData - Current form state
 * @param {Function} props.onChange - Handler for form updates
 */
export default function GrantNarrativeSection({ formData, onChange }) {
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);

  const handleChange = (field, value) => {
    onChange({ ...formData, [field]: value });
  };

  const hasExistingContent = () => {
    return formData.program_description || formData.eligibility_summary || formData.selection_criteria;
  };

  const handleGenerateSummary = async () => {
    if (!formData.title && !formData.url) {
      toast({
        variant: 'destructive',
        title: 'Missing Information',
        description: 'Please provide either a grant title or URL before using AI generation.'
      });
      return;
    }

    // Warn if overwriting
    if (hasExistingContent()) {
      const confirmed = window.confirm(
        'This will overwrite your existing program details. Continue?'
      );
      if (!confirmed) return;
    }

    setIsGenerating(true);

    try {
      const prompt = `You are a grant research specialist. Analyze this grant/scholarship opportunity and provide comprehensive program information.

${formData.title ? `GRANT TITLE: ${formData.title}` : ''}
${formData.funder ? `FUNDER: ${formData.funder}` : ''}
${formData.url ? `PROGRAM URL: ${formData.url}` : ''}
${formData.opportunity_type ? `TYPE: ${formData.opportunity_type}` : ''}

Search the internet for this opportunity and provide:

1. **Program Description** (2-3 paragraphs): What the grant/scholarship funds, the mission/purpose, key program goals, and typical activities or projects funded.

2. **Eligibility Summary** (bullet points): Who can apply - include specific requirements like:
   - Organization types or individual qualifications
   - Geographic restrictions
   - Budget/size requirements
   - Special certifications or registrations needed
   - Any exclusions or limitations

3. **Selection Criteria** (bullet points): How recipients are chosen:
   - Key evaluation factors
   - Scoring rubric elements
   - Priorities or preferences
   - Required components for strong applications

Be specific and detailed. Use information from the website if available. If you cannot find definitive information, indicate that in your response.

Return JSON with: program_description, eligibility_summary, and selection_criteria (all strings).`;

      const response = await base44.integrations.Core.InvokeLLM({
        prompt,
        add_context_from_internet: true,
        response_json_schema: {
          type: "object",
          properties: {
            program_description: { type: "string" },
            eligibility_summary: { type: "string" },
            selection_criteria: { type: "string" }
          }
        }
      });

      console.log('[GrantNarrativeSection] AI Response:', response);

      if (response.program_description || response.eligibility_summary || response.selection_criteria) {
        const updates = {};
        if (response.program_description) updates.program_description = response.program_description;
        if (response.eligibility_summary) updates.eligibility_summary = response.eligibility_summary;
        if (response.selection_criteria) updates.selection_criteria = response.selection_criteria;

        onChange({ ...formData, ...updates });

        // Log telemetry
        try {
          await base44.integrations.Core.InvokeLLM({
            prompt: `Log telemetry: grant_summary_autogenerated for grant "${formData.title || 'Untitled'}"`,
            response_json_schema: { type: "object", properties: {} }
          });
        } catch (e) {
          console.warn('[GrantNarrativeSection] Telemetry logging failed:', e);
        }

        toast({
          title: 'Program Details Generated! 🎯',
          description: 'AI has filled in the program information. Review and edit as needed.'
        });
      } else {
        toast({
          variant: 'destructive',
          title: 'No Information Found',
          description: 'AI could not generate program details. Try providing more information or adding details manually.'
        });
      }

    } catch (error) {
      console.error('[GrantNarrativeSection] Generation failed:', error);
      toast({
        variant: 'destructive',
        title: 'Generation Failed',
        description: error.message || 'Could not generate program details'
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-semibold text-slate-900">Program Details</h3>
          <p className="text-sm text-slate-600">Detailed information about the opportunity</p>
        </div>
        <Button
          type="button"
          onClick={handleGenerateSummary}
          disabled={isGenerating || (!formData.title && !formData.url)}
          variant="outline"
          className="bg-blue-50 border-blue-200 hover:bg-blue-100"
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2 text-blue-600" />
              Generate from Web
            </>
          )}
        </Button>
      </div>

      {hasExistingContent() && !isGenerating && (
        <Alert className="bg-amber-50 border-amber-200">
          <AlertCircle className="h-4 w-4 text-amber-600" />
          <AlertDescription className="text-amber-800 text-xs">
            Using AI generation will overwrite existing content. Save your work first if needed.
          </AlertDescription>
        </Alert>
      )}

      <div className="space-y-2">
        <Label htmlFor="program_description">
          Program Description
        </Label>
        <Textarea 
          id="program_description" 
          name="program_description" 
          value={formData.program_description || ''} 
          onChange={(e) => handleChange('program_description', e.target.value)} 
          rows={6}
          placeholder="Example: The Community Impact Grant supports local nonprofits in expanding programs that address food insecurity. Funded projects typically include food pantry expansions, mobile meal programs, and nutrition education initiatives. Priority is given to organizations serving rural and underserved communities."
        />
        <p className="text-xs text-slate-500">
          Describe what this opportunity funds and its goals
        </p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="eligibility_summary">
          Eligibility Summary
        </Label>
        <Textarea 
          id="eligibility_summary" 
          name="eligibility_summary" 
          value={formData.eligibility_summary || ''} 
          onChange={(e) => handleChange('eligibility_summary', e.target.value)} 
          rows={5}
          placeholder="Example:&#10;• 501(c)(3) nonprofits operating for at least 2 years&#10;• Serving populations in counties with poverty rate >15%&#10;• Annual budget between $100k-$5M&#10;• Must have Board of Directors and financial audit&#10;• Faith-based organizations eligible if services are secular"
        />
        <p className="text-xs text-slate-500">
          Who can apply? List specific requirements and restrictions
        </p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="selection_criteria">
          Selection Criteria
        </Label>
        <Textarea 
          id="selection_criteria" 
          name="selection_criteria" 
          value={formData.selection_criteria || ''} 
          onChange={(e) => handleChange('selection_criteria', e.target.value)} 
          rows={5}
          placeholder="Example:&#10;• Demonstrated community need (30 points)&#10;• Quality of program design and outcomes (25 points)&#10;• Organizational capacity and track record (20 points)&#10;• Budget reasonableness and sustainability (15 points)&#10;• Collaboration and partnerships (10 points)"
        />
        <p className="text-xs text-slate-500">
          How are recipients selected? Include scoring criteria if known
        </p>
      </div>
    </div>
  );
}