-- Hamilton credential vault: provenance + multiple logins per host.
--
-- managed_by marks WHO placed a credential so admin management surfaces can be
-- scoped to admin-placed rows only (an admin never sees a profile user's own
-- self-entered logins):
--   'admin'    - placed by an admin via CSV import or the admin vault panel
--   'user'     - entered by the profile's own user
--   'hamilton' - auto-generated by Hamilton
ALTER TABLE hamilton_portal_credentials ADD COLUMN IF NOT EXISTS managed_by TEXT;

-- Backfill existing rows. Admin-imported rows were saved under the synthetic
-- admin user id 'system_admin_token'; generated rows have generated_by set.
UPDATE hamilton_portal_credentials SET managed_by = 'admin'
  WHERE managed_by IS NULL AND user_id = 'system_admin_token';
UPDATE hamilton_portal_credentials SET managed_by = 'hamilton'
  WHERE managed_by IS NULL AND generated_by IS NOT NULL;
UPDATE hamilton_portal_credentials SET managed_by = 'user'
  WHERE managed_by IS NULL;

-- Allow multiple logins per (profile, host) by keying uniqueness on username
-- too. The old (profile, host) unique index collapsed multi-account sites
-- (e.g. several PayPal logins) to a single row.
DROP INDEX IF EXISTS ux_hamilton_portal_cred_profile_host;
CREATE UNIQUE INDEX IF NOT EXISTS ux_hamilton_portal_cred_profile_host_user
  ON hamilton_portal_credentials(profile_id, portal_host, username);
CREATE INDEX IF NOT EXISTS idx_hamilton_portal_cred_managed_by
  ON hamilton_portal_credentials(managed_by);
