// Canonical "Comprehensive Profile Application" schema template.
// This is used to ensure every profile (existing + new) can store every data point,
// even if the UI only renders a subset of structured editors.

export const REQUIRED_PROFILE_SECTION_KEYS = [
  // Structured sections used by the UI + enrichment
  'basic_information',
  'organization_details',
  'financial_information',
  'government_assistance',
  'health_medical',
  'demographics',
  'family_life',
  'military_service',
  'occupation',
  'location_focus',
  'narrative',

  // Student-focused sections
  'education',
  'university_applications',

  // Full canonical application payload (complete parity with the comprehensive form)
  'comprehensive_application',
]

export const PROFILE_SECTION_DEFAULTS = {
  basic_information: {
    full_name: '',
    email: '',
    phone: '',
    website: '',
    address: '',
    notes: '',
  },
  organization_details: {
    organization_type: '',
    ein: '',
    uei: '',
    cage_code: '',
    annual_budget: null,
    staff_count: null,
    mission: '',
  },
  financial_information: {
    household_income: null,
    household_size: null,
    financial_need_level: '',
    low_income: false,
    unemployed: false,
    displaced_worker: false,
    notes: '',
  },
  government_assistance: {
    medicaid_enrolled: false,
    medicare_recipient: false,
    ssi_recipient: false,
    ssdi_recipient: false,
    snap_recipient: false,
    tanf_recipient: false,
    section8_housing: false,
    other_programs: '',
  },
  health_medical: {
    chronic_illness: false,
    chronic_illness_type: '',
    disability_type: [],
    support_needs_level: '',
    dialysis_patient: false,
    organ_transplant: false,
    hiv_aids: false,
    tbi_survivor: false,
    amputee: false,
    neurodivergent: false,
    visual_impairment: false,
    hearing_impairment: false,
    wheelchair_user: false,
    substance_recovery: false,
    mental_health_condition: false,
    notes: '',
  },
  demographics: {
    african_american: false,
    hispanic_latino: false,
    asian_american: false,
    native_american: false,
    tribal_affiliation: '',
    lgbtq: false,
    immigrant_status: '',
    notes: '',
  },
  family_life: {
    single_parent: false,
    foster_youth: false,
    orphan: false,
    adopted: false,
    foster_parent: false,
    caregiver: false,
    widow_widower: false,
    grandparent_raising_grandchildren: false,
    first_time_parent: false,
    homeless: false,
    domestic_violence_survivor: false,
    trafficking_survivor: false,
    disaster_survivor: false,
    formerly_incarcerated: false,
    notes: '',
  },
  military_service: {
    veteran: false,
    active_duty_military: false,
    national_guard: false,
    disabled_veteran: false,
    military_spouse: false,
    military_dependent: false,
    gold_star_family: false,
    notes: '',
  },
  occupation: {
    healthcare_worker: false,
    healthcare_worker_type: '',
    ems_worker: false,
    educator: false,
    firefighter: false,
    law_enforcement: false,
    public_servant: false,
    clergy: false,
    missionary: false,
    nonprofit_employee: false,
    small_business_owner: false,
    minority_owned_business: false,
    women_owned_business: false,
    union_member: false,
    farmer: false,
    truck_driver: false,
    notes: '',
  },
  location_focus: {
    rural_resident: false,
    appalachian_region: false,
    urban_underserved: false,
    geographic_focus: '',
    notes: '',
  },
  narrative: {
    mission: '',
    primary_goal: '',
    target_population: '',
    funding_amount_needed: '',
    timeline: '',
    past_experience: '',
    unique_qualities: '',
    collaboration_partners: '',
    sustainability_plan: '',
    barriers_faced: '',
    special_circumstances: '',
  },

  // Student: education record / transcript sending hubs
  education: {
    current_school: '',
    current_school_contact: {
      name: '',
      title: '',
      email: '',
      phone: '',
      url: '',
      notes: '',
    },
    past_schools: [],
    transcript_portal_url: '',
    test_scores_portal_url: '',
    commonapp_profile_url: '',
    fafsa_portal_url: 'https://studentaid.gov/h/apply-for-aid/fafsa',
    notes: '',
  },

  // Student: schools list (Base44-like cards)
  university_applications: {
    applications: [],
  },

  // Full comprehensive form payload for parity (leave blanks when not applicable).
  comprehensive_application: {
    version: 1,
    custom_fields: {},
    primary_profile_type: {
      primary_type: '',
      other: '',
    },
    basic_information: {
      full_name_or_organization_name: '',
      date_of_birth: '',
      age: '',
      social_security_number: '',
      green_card_number: '',
      emails: [],
      phones: [],
      website: '',
    },
    address: {
      street_address: '',
      city: '',
      state: '',
      zip: '',
    },
    organization_details: {
      ein: '',
      uei: '',
      cage_code: '',
      organization_type: '',
      annual_budget_usd: null,
      staff_count: null,
      federal_registration_compliance: {
        sam_gov_registered: false,
        grants_gov_account_active: false,
        era_commons_account: false,
        state_vendor_registration: false,
        charitable_solicitation_registration: false,
        sam_exclusions_check_passed: false,
        notes: '',
      },
      financial_audit_status: {
        audited_financials_available: false,
        single_audit_most_recent_year: '',
        nicra: {
          has_nicra: false,
          rate_percent: null,
          notes: '',
        },
      },
      general_qualifications: {
        faith_based: false,
        serves_rural_area: false,
        minority_serving_organization: false,
        is_501c3_public_charity: false,
        is_501c3_private_foundation: false,
        ntee_code: '',
        evidence_based_program_model: '',
        data_protections: {
          hipaa: false,
          ferpa: false,
          cfr_42_part_2: false,
        },
      },
      partnerships_mous: {
        schools_or_districts: false,
        hospitals_or_health_systems: false,
        universities_or_colleges: false,
        tribal_governments: false,
        other: '',
      },
      insurance_risk_management: {
        general_liability_coverage_limits_usd: null,
        workers_comp: false,
        cyber_insurance: false,
      },
      business_certifications: {
        certified_8a: false,
        sdvosb: false,
        hubzone: false,
        dbe: false,
        mbe: false,
        wbe: false,
        sbe: false,
        minority_owned_business: false,
        women_owned_business: false,
        sbir_sttr_eligible: false,
      },
      geographic_special_designations: {
        qualified_census_tract_qct: false,
        opportunity_zone: false,
        epa_environmental_justice_area: false,
        usda_persistent_poverty_county: false,
        tribal_reservation_or_trust_land: false,
        us_territory: false,
        fema_disaster_declaration_area: false,
        appalachian_region: false,
        urban_underserved_area: false,
        promise_zone: false,
        choice_neighborhood: false,
        delta_regional_authority_region: false,
        northern_border_commission_region: false,
        denali_commission_region: false,
        colonias_designation: false,
        new_markets_tax_credit_eligible_tract: false,
        brownfield_site_status: false,
        broadband_unserved_fcc_map_block: false,
        wildland_urban_interface_fire_risk: false,
        floodplain_location: false,
        crs_score: '',
      },
      notes: '',
    },
    education_information: {
      grade_levels: [],
      education_type_setting: [],
      current_college_or_university: '',
      target_or_interested_colleges: [],
      intended_major_or_field: '',
      planned_enrollment_term: {
        term: '',
        year: '',
      },
      gpa: '',
      standardized_test_scores: {
        act: '',
        sat: '',
        gre: '',
        gmat: '',
        lsat: '',
        mcat: '',
      },
      community_service_hours: '',
      qualifiers: {
        attends_title_i_school: false,
        iep_504_status: false,
        idea_disability_category: '',
        cte_pathway: '',
        dual_enrollment_early_college: false,
        rotc_jrotc: false,
        civil_air_patrol: false,
        honor_societies: [],
        competitions_awards: [],
        work_study_eligible: false,
        efc_sai_band: '',
        student_housing_status: [],
        faith_based_college_attendance: false,
        athletics_commitment: false,
        arts_commitment: false,
        academic_characteristics: [],
        pell_grant_eligible: false,
        fafsa_completed: false,
      },
      notes: '',
    },
    financial_situation: {
      annual_household_income_usd: null,
      household_size: null,
      financial_challenges: [],
    },
    government_assistance_programs: {
      programs: [],
      medicaid_number: '',
      medicaid_waiver_programs: [],
      other: '',
    },
    health_medical_conditions: {
      conditions: [],
      notes: '',
    },
    demographics_background: {
      immigration_citizenship_status: '',
      race_ethnicity: [],
      tribal_affiliation: '',
      cultural_ethnic_heritage: [],
      religious_affiliation: [],
      lgbtq: false,
      good_credit_score_700_plus: false,
      notes: '',
    },
    family_life_situation: {
      flags: [],
      notes: '',
    },
    military_service: {
      flags: [],
      branch_mos: '',
      campaign_medals: '',
      character_of_discharge: '',
      va_disability_rating_percent: null,
      recent_activation_date: '',
      relationship_gold_star: '',
      notes: '',
    },
    occupation_work: {
      roles: [],
      healthcare_worker: {
        type: '',
        licensure_certifications: '',
      },
      farmer: {
        farm_acreage: '',
        usda_programs: [],
      },
      union_local_apprenticeship_registration: '',
      notes: '',
    },
    firearms_second_amendment: {
      flags: [],
      states_licensed: [],
      notes: '',
    },
    political_civic_engagement: {
      flags: [],
      office_held: '',
      years_in_office: '',
      political_party_affiliation: '',
      party_leadership_position: '',
      level_of_engagement: [],
      type_of_office_role: '',
      campaign_finance_experience: false,
      policy_expertise_areas: [],
      support_organizations: [],
      notes: '',
    },
    story_goals: {
      goals: '',
      unique_story: '',
      funding_need_and_use: '',
      challenges_or_barriers: '',
      support_network: '',
    },
    additional_information: {
      extracurricular_activities_interests: [],
      awards_achievements: [],
      keywords: [],
      notes: '',
    },
    signature: {
      signature: '',
      date: '',
    },
  },
}

