import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { 
  CheckCircle, 
  AlertTriangle, 
  Sparkles, 
  Edit, 
  Mail, 
  Phone, 
  MapPin,
  Clock,
  Shield,
  Send,
  Printer
} from 'lucide-react';
import { format } from 'date-fns';

/**
 * Contact verification card with AI re-verification and manual override
 */
export default function ContactVerificationCard({ 
  grant, 
  onReverify, 
  onManualVerify, 
  isVerifying,
  onSubmit
}) {
  const [showNotesEditor, setShowNotesEditor] = useState(false);
  const [notes, setNotes] = useState(grant?.contact_notes || '');

  const hasContactInfo = grant.funder_email || grant.funder_phone || grant.funder_fax || grant.funder_address;
  const isVerified = grant.contact_verified;
  
  // Count how many contact data points we have
  const contactDataPoints = [
    grant.funder_email,
    grant.funder_phone,
    grant.funder_fax,
    grant.funder_address
  ].filter(Boolean).length;

  const handleSaveNotes = () => {
    onManualVerify(notes);
    setShowNotesEditor(false);
  };

  if (!hasContactInfo) {
    return (
      <Card className="border-2 border-amber-200 bg-amber-50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-amber-900">
            <AlertTriangle className="w-5 h-5" />
            No Contact Information Available
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-amber-800 text-sm">
            Contact information for this funder is not available. Use AI to search for contact details.
          </p>
          <div className="flex flex-wrap gap-2">
            <Button 
              onClick={onReverify}
              disabled={isVerifying || !grant.funder}
              className="bg-amber-600 hover:bg-amber-700"
            >
              {isVerifying ? (
                <>
                  <Sparkles className="w-4 h-4 mr-2 animate-spin" />
                  Searching...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Find Contact Info with AI
                </>
              )}
            </Button>
            {onSubmit && (
              <Button 
                onClick={onSubmit}
                className="bg-green-600 hover:bg-green-700"
              >
                <Send className="w-4 h-4 mr-2" />
                Submit Now
              </Button>
            )}
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={`border-2 ${isVerified ? 'border-green-200 bg-green-50' : 'border-amber-200 bg-amber-50'}`}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            {isVerified ? (
              <>
                <CheckCircle className="w-5 h-5 text-green-600" />
                <span className="text-green-900">Funder Contact Information</span>
              </>
            ) : (
              <>
                <AlertTriangle className="w-5 h-5 text-amber-600" />
                <span className="text-amber-900">Unverified Contact Information</span>
              </>
            )}
          </CardTitle>
          <Badge variant={isVerified ? "default" : "secondary"} className={isVerified ? "bg-green-600" : "bg-amber-600"}>
            {isVerified ? "Verified ✓" : "AI-Generated"}
          </Badge>
        </div>
      </CardHeader>
      
      <CardContent className="space-y-4">
        {/* Verification Status Alert */}
        {!isVerified ? (
          <Alert className="border-amber-300 bg-amber-100">
            <Shield className="h-4 w-4 text-amber-600" />
            <AlertTitle className="text-amber-900">Verification Needed</AlertTitle>
            <AlertDescription className="text-amber-800 text-sm">
              This contact information was automatically generated by AI and should be verified before use in your application.
            </AlertDescription>
          </Alert>
        ) : (
          <Alert className="border-green-300 bg-green-100">
            <CheckCircle className="h-4 w-4 text-green-600" />
            <AlertDescription className="text-green-800 text-sm flex items-center justify-between">
              <div>
                <strong>Verified Contact Information</strong>
                {grant.contact_verified_date && (
                  <div className="flex items-center gap-1 mt-1 text-xs">
                    <Clock className="w-3 h-3" />
                    <span>Verified on {format(new Date(grant.contact_verified_date), 'MMM d, yyyy')}</span>
                  </div>
                )}
              </div>
            </AlertDescription>
          </Alert>
        )}

        {/* Contact Info Found Alert */}
        {contactDataPoints > 0 && (
          <Alert className="border-green-300 bg-green-100">
            <Sparkles className="h-4 w-4 text-green-600" />
            <AlertTitle className="text-green-900">Contact Info Found! ✨</AlertTitle>
            <AlertDescription className="text-green-800 text-sm">
              Found {contactDataPoints} contact detail{contactDataPoints !== 1 ? 's' : ''}. Review and edit as needed.
            </AlertDescription>
          </Alert>
        )}

        {/* Contact Details */}
        <div className="grid gap-3">
          {grant.funder_email && (
            <div className="flex items-start gap-3 p-3 bg-white rounded-lg border border-slate-200">
              <Mail className="w-5 h-5 text-blue-600 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-xs text-slate-500 mb-1">Email</p>
                <a 
                  href={`mailto:${grant.funder_email}`}
                  className="text-sm font-medium text-blue-600 hover:underline break-all"
                >
                  {grant.funder_email}
                </a>
              </div>
            </div>
          )}

          {grant.funder_phone && (
            <div className="flex items-start gap-3 p-3 bg-white rounded-lg border border-slate-200">
              <Phone className="w-5 h-5 text-green-600 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-xs text-slate-500 mb-1">Phone Number</p>
                <a 
                  href={`tel:${grant.funder_phone}`}
                  className="text-sm font-medium text-slate-900 hover:text-green-600"
                >
                  {grant.funder_phone}
                </a>
              </div>
            </div>
          )}

          {grant.funder_fax && (
            <div className="flex items-start gap-3 p-3 bg-white rounded-lg border border-slate-200">
              <Printer className="w-5 h-5 text-slate-600 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-xs text-slate-500 mb-1">Fax Number</p>
                <p className="text-sm font-medium text-slate-900">
                  {grant.funder_fax}
                </p>
              </div>
            </div>
          )}

          {grant.funder_address && (
            <div className="flex items-start gap-3 p-3 bg-white rounded-lg border border-slate-200">
              <MapPin className="w-5 h-5 text-purple-600 mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-xs text-slate-500 mb-1">Mailing Address</p>
                <p className="text-sm font-medium text-slate-900 whitespace-pre-line">
                  {grant.funder_address}
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Verification Notes */}
        {grant.contact_notes && !showNotesEditor && (
          <div className="p-3 bg-white rounded-lg border border-slate-200">
            <p className="text-xs text-slate-500 mb-1">Verification Notes</p>
            <p className="text-sm text-slate-700">{grant.contact_notes}</p>
          </div>
        )}

        {/* Notes Editor */}
        {showNotesEditor && (
          <div className="space-y-3">
            <div>
              <Label className="text-sm">Verification Notes</Label>
              <Textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="E.g., 'Confirmed email via website contact page' or 'Called and verified phone number'"
                rows={3}
                className="mt-1"
              />
            </div>
            <div className="flex gap-2">
              <Button onClick={handleSaveNotes} size="sm">
                <CheckCircle className="w-4 h-4 mr-2" />
                Save & Mark as Verified
              </Button>
              <Button 
                variant="outline" 
                onClick={() => setShowNotesEditor(false)}
                size="sm"
              >
                Cancel
              </Button>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        {!showNotesEditor && (
          <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-200">
            <Button 
              variant="outline" 
              size="sm"
              onClick={onReverify}
              disabled={isVerifying}
              className="flex-1 sm:flex-none"
            >
              {isVerifying ? (
                <>
                  <Sparkles className="w-3 h-3 mr-2 animate-spin" />
                  Re-verifying...
                </>
              ) : (
                <>
                  <Sparkles className="w-3 h-3 mr-2" />
                  Re-verify with AI
                </>
              )}
            </Button>
            
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => setShowNotesEditor(true)}
              className="flex-1 sm:flex-none"
            >
              <Edit className="w-3 h-3 mr-2" />
              {isVerified ? 'Update Notes' : 'Verify Manually'}
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}