import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const sdk = vi.hoisted(() => ({ openai: vi.fn(), anthropic: vi.fn(), construct: vi.fn() }))
vi.mock('openai', () => ({ default: class { constructor(options) { sdk.construct(options); this.chat = { completions: { create: sdk.openai } } } } }))
vi.mock('@anthropic-ai/sdk', () => ({ default: class { messages = { create: sdk.anthropic } } }))
import { invokeJsonWithFallback, invokeTextWithFallback } from '../utils/aiProviders.js'
import { clearRecentLogs, getRecentLogs } from '../utils/logger.js'
import { circuitBlocked, recordPaidFailure } from '../utils/paidAiRoutes.js'
const completion = (content = '{"ok":true}', finish_reason = 'stop') => ({ choices: [{ message: { content }, finish_reason }] })
const config = (routes) => vi.stubEnv('AI_PAID_ROUTES', JSON.stringify(routes))
const routes = [{ provider: 'openai', model: 'gpt-4.1' }, { provider: 'anthropic', model: 'claude-sonnet-4-6' }, { provider: 'openai', model: 'gpt-4.1-mini' }]
let state
const run = (options = {}) => invokeJsonWithFallback({ prompt: 'fixture', freeRoutes: [], paidCircuitState: state, ...options })
beforeEach(() => {
  vi.clearAllMocks(); clearRecentLogs(); state = new Map()
  vi.stubEnv('OPENAI_API_KEY', 'fixture-key'); vi.stubEnv('ANTHROPIC_API_KEY', 'fixture-anthropic')
  config(routes)
  sdk.openai.mockResolvedValue(completion()); sdk.anthropic.mockResolvedValue({ content: [{ text: '{"ok":true}' }] })
})
afterEach(() => { vi.unstubAllEnvs(); vi.useRealTimers() })
describe('ranked paid gateway', () => {
  it('promotes the other primary ahead of consecutive models from the first provider', async () => {
    config([routes[0], routes[2], routes[1]])
    sdk.openai.mockRejectedValueOnce(new Error('unavailable'))
    expect(await run()).toMatchObject({ provider: 'anthropic' })
    expect(sdk.openai).toHaveBeenCalledTimes(1)
  })
  it('preserves explicit null opt-out with configured OpenAI routes', async () => {
    expect(await run({ openai: null })).toMatchObject({ provider: 'anthropic' })
    expect(sdk.openai).not.toHaveBeenCalled()
  })
  it('bounds cached failures and expires them without storing credentials', () => {
    vi.useFakeTimers()
    for (let i = 0; i < 400; i++) recordPaidFailure(state, { account: String(i), model: 'fixture' }, new Error('unavailable'))
    expect(state.size).toBe(256)
    vi.advanceTimersByTime(5001)
    expect(circuitBlocked(state, { account: '399', model: 'fixture' })).toBe(false)
    expect(state.size).toBe(0)
  })
  it('honors short Retry-After without treating rate limit as account exhaustion', async () => {
    vi.useFakeTimers()
    sdk.openai.mockRejectedValueOnce(Object.assign(new Error('rate limited'), { status: 429, headers: new Headers({ 'retry-after': '2' }) }))
    sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    expect(await run()).toMatchObject({ model: 'gpt-4.1-mini' })
    vi.advanceTimersByTime(2001)
    expect(await run()).toMatchObject({ model: 'gpt-4.1' })
  })
  it('does not restart a zero budget or continue after cancellation', async () => {
    expect(await run({ timeoutMs: 0 })).toMatchObject({ ok: false })
    expect(sdk.openai).not.toHaveBeenCalled()
    vi.useFakeTimers()
    const controller = new AbortController()
    sdk.openai.mockImplementationOnce(() => new Promise(() => {}))
    const pending = run({ signal: controller.signal })
    await vi.advanceTimersByTimeAsync(1)
    controller.abort()
    expect(await pending).toMatchObject({ aborted: true })
    expect(sdk.openai.mock.calls[0][1].signal.aborted).toBe(true)
    expect(sdk.anthropic).not.toHaveBeenCalled()
  })
  it('rejects truncated free JSON even when its prefix parses', async () => {
    config([])
    const create = vi.fn().mockResolvedValue(completion('{"partial":true}', 'length'))
    expect(await run({ freeRoutes: [{ model: 'fixture', base_url: 'https://fixture.invalid/v1' }], freeClientFactory: () => ({ chat: { completions: { create } } }) })).toMatchObject({ ok: false })
  })
  it('rejects malformed free JSON with a valid object prefix', async () => {
    config([])
    const create = vi.fn().mockResolvedValue(completion('{"partial":true} trailing garbage'))
    expect(await run({ freeRoutes: [{ model: 'fixture', base_url: 'https://fixture.invalid/v1' }], freeClientFactory: () => ({ chat: { completions: { create } } }) })).toMatchObject({ ok: false })
  })
  it('uses configured primary then other primary before remaining ranked models', async () => {
    sdk.openai.mockRejectedValueOnce(new Error('unavailable'))
    expect(await run()).toMatchObject({ provider: 'anthropic', model: 'claude-sonnet-4-6', billing_mode: 'paid_api' })
    expect(sdk.openai.mock.calls[0][0].model).toBe('gpt-4.1')
  })
  it('supports Anthropic first', async () => {
    config([routes[1], routes[0], routes[2]])
    sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    expect(await run()).toMatchObject({ provider: 'openai', model: 'gpt-4.1' })
    expect(sdk.anthropic.mock.invocationCallOrder[0]).toBeLessThan(sdk.openai.mock.invocationCallOrder[0])
  })
  it('tries the next paid model before free after both primary failures', async () => {
    sdk.openai.mockRejectedValueOnce(new Error('unavailable')); sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    expect(await run()).toMatchObject({ provider: 'openai', model: 'gpt-4.1-mini' })
    expect(sdk.openai.mock.calls.map(([a]) => a.model)).toEqual(['gpt-4.1', 'gpt-4.1-mini'])
  })
  it('reaches existing free routes only after the paid ladder', async () => {
    sdk.openai.mockRejectedValue(new Error('unavailable')); sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    const create = vi.fn().mockResolvedValue(completion())
    const result = await run({ freeRoutes: [{ id: 'fixture', model: 'free', base_url: 'http://fixture.invalid/v1' }], freeClientFactory: () => ({ chat: { completions: { create } } }) })
    expect(result).toMatchObject({ provider: 'free:fixture', model: 'free', billing_mode: 'free_or_local' })
    expect(sdk.openai).toHaveBeenCalledTimes(2)
  })
  it('skips exhausted account models, expires cooldown, and invalidates on rotation', async () => {
    vi.useFakeTimers()
    sdk.openai.mockRejectedValue(Object.assign(new Error('insufficient_quota private-secret'), { status: 429 }))
    sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    await run(); expect(sdk.openai).toHaveBeenCalledTimes(1)
    await run(); expect(sdk.openai).toHaveBeenCalledTimes(1)
    vi.stubEnv('OPENAI_API_KEY', 'rotated-key'); await run(); expect(sdk.openai).toHaveBeenCalledTimes(2)
    await vi.advanceTimersByTimeAsync(300001); await run(); expect(sdk.openai).toHaveBeenCalledTimes(3)
    expect(JSON.stringify([...state])).not.toContain('key')
  })
  it('rate limit is model scoped and Retry-After is bounded', async () => {
    vi.useFakeTimers()
    sdk.openai.mockRejectedValueOnce(Object.assign(new Error('rate limited'), { status: 429, headers: { 'retry-after': '999999' } }))
    sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    expect(await run()).toMatchObject({ model: 'gpt-4.1-mini' })
    sdk.openai.mockClear(); await run(); expect(sdk.openai.mock.calls[0][0].model).toBe('gpt-4.1-mini')
    await vi.advanceTimersByTimeAsync(300001); sdk.openai.mockClear(); await run(); expect(sdk.openai.mock.calls[0][0].model).toBe('gpt-4.1')
  })
  it('times out only the model, aborts its request, and reserves later paid time', async () => {
    vi.useFakeTimers()
    sdk.openai.mockImplementationOnce(() => new Promise(() => {})); sdk.anthropic.mockRejectedValue(new Error('unavailable'))
    const pending = run({ timeoutMs: 10000 })
    await vi.advanceTimersByTimeAsync(10000)
    expect(await pending).toMatchObject({ ok: true, model: 'gpt-4.1-mini' })
    expect(sdk.openai.mock.calls[0][1].signal.aborted).toBe(true)
  })
  it.each(['', 'garbage', '{"ok":true} trailing garbage'])('rejects invalid JSON %j without accepting it', async (content) => {
    sdk.openai.mockResolvedValueOnce(completion(content))
    expect(await run()).toMatchObject({ provider: 'anthropic', billing_mode: 'paid_api' })
  })
  it('rejects empty text and Anthropic truncated JSON', async () => {
    sdk.openai.mockResolvedValueOnce(completion(' '))
    expect(await invokeTextWithFallback({ prompt: 'fixture', freeRoutes: [], paidCircuitState: state })).toMatchObject({ provider: 'anthropic' })
    config([routes[1], routes[0]])
    sdk.anthropic.mockResolvedValue({ stop_reason: 'max_tokens', content: [{ text: '{"partial":true}' }] })
    expect(await run({ paidCircuitState: new Map() })).toMatchObject({ provider: 'openai' })
  })
  it('uses reasoning parameters and refuses Responses-only chat routes', async () => {
    config([{ provider: 'openai', model: 'gpt-5.4' }])
    await run()
    expect(sdk.openai.mock.calls[0][0]).toMatchObject({ max_completion_tokens: 1200 })
    expect(sdk.openai.mock.calls[0][0]).not.toHaveProperty('temperature')
    config([{ provider: 'openai', model: 'gpt-5.4-pro', api: 'responses' }]); sdk.openai.mockClear()
    await run(); expect(sdk.openai.mock.calls.some(([a]) => a.model === 'gpt-5.4-pro')).toBe(false)
  })
  it('allows only dedicated compatible credentials and excludes raw errors from logs', async () => {
    vi.stubEnv('PAID_AI_ROUTE_FIXTURE_API_KEY', 'dedicated-secret')
    config([{ provider: 'compatible', model: 'fixture-model', base_url: 'https://paid.example.test/v1', api_key_env: 'DATABASE_URL' }, { provider: 'compatible', model: 'fixture-model', base_url: 'https://paid.example.test/v1', api_key_env: 'PAID_AI_ROUTE_FIXTURE_API_KEY' }])
    sdk.openai.mockRejectedValue(new Error('private-provider-message dedicated-secret')); sdk.anthropic.mockRejectedValue(new Error('private-provider-message'))
    await run()
    expect(sdk.construct.mock.calls.some(([a]) => a.apiKey === 'dedicated-secret')).toBe(true)
    expect(sdk.construct.mock.calls.filter(([a]) => a.baseURL).length).toBe(1)
    const logs = JSON.stringify(getRecentLogs())
    expect(logs).not.toContain('private-provider-message'); expect(logs).not.toContain('dedicated-secret')
  })
})
