-- Seed a minimal set of nationwide opportunities so the UI isn't empty on fresh Postgres.
-- Idempotent: ON CONFLICT DO NOTHING.

INSERT INTO funding_opportunities (
  id,
  created_at,
  updated_at,
  title,
  sponsor,
  source,
  source_id,
  source_url,
  record_origin,
  description,
  eligibility_bullets,
  is_national,
  state,
  categories,
  keywords,
  opportunity_type,
  type,
  is_active
) VALUES
(
  'seed_national_211',
  now(),
  now(),
  '211 Helpline & Local Assistance Directory',
  'United Way / Local 211 Partners',
  'curated_verified',
  '211',
  'https://www.211.org/',
  'curated_verified',
  'Find local help for food, housing, utilities, medical care, and more by ZIP code.',
  '["Varies by program","Available nationwide via local directories"]',
  TRUE,
  'nationwide',
  '["benefit","directory"]',
  '["housing","food","utilities","medical","emergency"]',
  'program',
  'DIRECTORY',
  TRUE
),
(
  'seed_national_benefits_gov',
  now(),
  now(),
  'Benefits.gov Finder',
  'U.S. Government',
  'curated_verified',
  'benefits.gov',
  'https://www.benefits.gov/',
  'curated_verified',
  'Official federal benefits finder to discover programs you may qualify for.',
  '["Eligibility varies","Use the questionnaire to discover programs"]',
  TRUE,
  'nationwide',
  '["benefit","directory"]',
  '["benefits","federal","assistance"]',
  'program',
  'DIRECTORY',
  TRUE
),
(
  'seed_national_grants_gov',
  now(),
  now(),
  'Grants.gov Opportunities Search',
  'U.S. Government',
  'curated_verified',
  'grants.gov',
  'https://www.grants.gov/search-grants',
  'curated_verified',
  'Official federal grants portal for organizations, nonprofits, and other eligible applicants.',
  '["Eligibility varies by grant","Organizations/nonprofits often required"]',
  TRUE,
  'nationwide',
  '["grant","federal"]',
  '["grants","federal","nonprofit"]',
  'grant',
  'OPPORTUNITY',
  TRUE
)
ON CONFLICT (id) DO NOTHING;

