import React from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'

import { PricingRecommendationPanel } from '@/components/pricing/PricingRecommendationPanel'

/**
 * Admin section: reviews pricing recommendations generated by Anya
 * intake. Designed to be dropped into the existing Admin page as a card
 * or section.
 */
export function AdminPricingRecommendations() {
  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Pricing — Anya intake recommendations</CardTitle>
          <CardDescription>
            Internal-only by default. The user only sees a gentle estimate when
            <code className="mx-1 rounded bg-muted px-1">PRICING_SHOW_CLIENT_ESTIMATE=true</code>
            is set on the server. Approve, edit, and present quotes here.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <PricingRecommendationPanel />
        </CardContent>
      </Card>
    </div>
  )
}

export default AdminPricingRecommendations
