// Payload-wide diagnostic redaction.
//
// App processes and browser errors are untrusted text. They may echo a launch
// secret, a credential-bearing URL, an Authorization header, or a private home
// directory. Every app result passes through this module immediately before it
// is signed and uploaded; individual outcome builders therefore cannot
// accidentally create a new unredacted transport path.

const REDACTED = '[REDACTED]'

function replaceAllLiteral(text, needle) {
  return needle ? text.split(needle).join(REDACTED) : text
}

/** Redact one diagnostic string without destroying useful host/port context. */
export function redactDiagnosticText(value, { sensitiveValues = [] } = {}) {
  let text = String(value ?? '')

  // Values generated by EVA or supplied through EVA_APP_ENV are the strongest
  // signal. Replace longest first so one secret that prefixes another cannot
  // leave a suffix behind. Very short values ("1", "true", a port) are never
  // treated as secrets because replacing them would destroy the diagnostic.
  const exact = [...new Set((sensitiveValues || []).map((v) => String(v ?? '')).filter((v) => v.length >= 6))]
    .sort((a, b) => b.length - a.length)
  for (const secret of exact) text = replaceAllLiteral(text, secret)

  // Credential-bearing URLs retain scheme/host/path while dropping userinfo.
  text = text.replace(/\b([a-z][a-z0-9+.-]*:\/\/)([^\s/@]+)@/gi, `$1${REDACTED}@`)

  // Authorization headers and common opaque token formats.
  text = text.replace(/\b(Bearer|Basic)\s+[A-Za-z0-9._~+/=-]+/gi, `$1 ${REDACTED}`)
  text = text.replace(/\beyJ[A-Za-z0-9_-]{8,}[.]eyJ[A-Za-z0-9_-]{8,}[.][A-Za-z0-9_-]{8,}\b/g, REDACTED)
  text = text.replace(/\b(?:sk|pk|rk)-(?:live|test|proj)?-?[A-Za-z0-9_-]{12,}\b/gi, REDACTED)

  const key = '(?:password|passwd|pwd|secret|token|api[_-]?key|private[_-]?key|authorization|auth[_-]?jwt[_-]?secret|cookie[_-]?secret|encryption[_-]?key)'
  // JSON/quoted assignments: "JWT_SECRET":"value" and KEY='value'.
  text = text.replace(new RegExp(`(["']?${key}["']?\\s*[:=]\\s*)(["'])([^"'\\r\\n]*)(\\2)`, 'gi'), `$1$2${REDACTED}$4`)
  // Shell/log assignments: JWT_SECRET=value or password: value.
  text = text.replace(new RegExp(`(\\b${key}\\b\\s*[:=]\\s*)(?!${REDACTED.replace(/[\[\]]/g, '\\$&')})[^\\s|,;&]+`, 'gi'), `$1${REDACTED}`)
  // Sensitive URL query parameters.
  text = text.replace(new RegExp(`([?&]${key}=)[^&#\\s]+`, 'gi'), `$1${REDACTED}`)

  // Private workstation identities should not enter coordinator records or
  // owner emails. Keep the rest of the path so candidate-file diagnostics are
  // still actionable.
  text = text.replace(/\b([A-Za-z]:[\\/]Users[\\/])[^\\/\s]+/gi, '$1[user]')
  text = text.replace(/\/(home|Users)\/[^/\s]+/g, '/$1/[user]')
  text = text.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+[.][A-Z]{2,}\b/gi, '[REDACTED_EMAIL]')

  return text
}

/** Recursively redact strings while preserving the payload's shape. */
export function redactDiagnosticValue(value, options = {}) {
  if (typeof value === 'string') return redactDiagnosticText(value, options)
  if (Array.isArray(value)) return value.map((item) => redactDiagnosticValue(item, options))
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(
    Object.entries(value).map(([key, child]) => [key, redactDiagnosticValue(child, options)]),
  )
}
