export const baselineProfiles = [
  {
    id: 'profile-axiom-community-health',
    display_name: 'Axiom Community Health Cooperative',
    primary_type: 'nonprofit',
    status: 'active',
    tags: ['healthcare', 'rural', 'behavioral health'],
    organization: {
      id: 'org-axiom-community-health',
      name: 'Axiom Community Health Cooperative',
      applicant_type: 'nonprofit',
      email: 'hello@axiomhealth.org',
      phone: '615-555-2010',
      website: 'https://axiomhealth.org',
      address: '125 Maple Street',
      city: 'Cookeville',
      state: 'TN',
      zip: '38501',
      annual_budget: 850000,
      staff_count: 28,
      mission: 'Deliver integrated primary care and counseling for rural Tennessee families.',
      keywords: ['healthcare', 'behavioral health', 'rural'],
      focus_areas: ['Rural health access'],
      program_areas: ['Mobile counseling teams'],
      funding_amount_needed: 'Launch two mobile behavioral health crews with telehealth support.',
    },
    sections: {
      basic_information: {
        full_name: 'Axiom Community Health Cooperative',
        email: 'hello@axiomhealth.org',
        phone: '615-555-2010',
        website: 'https://axiomhealth.org',
        address: '125 Maple Street\nCookeville, TN 38501',
      },
      organization_details: {
        organization_type: 'Federally qualified health center',
        mission: 'Keep rural families stable through integrated medical and counseling services.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: false,
        notes: 'Bridge funding needed until HRSA renewal finalises.',
      },
      government_assistance: {
        medicaid_enrolled: true,
        snap_recipient: false,
        other_programs: 'HRSA rural health clinic reimbursement.',
      },
      health_medical: {
        support_needs_level: 'High',
        mental_health_condition: true,
      },
      demographics: {
        african_american: false,
        native_american: false,
      },
      family_life: {
        caregiver: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        nonprofit_employee: true,
        healthcare_worker: true,
      },
      location_focus: {
        rural_resident: true,
        appalachian_region: true,
        geographic_focus: 'Upper Cumberland counties',
      },
      narrative: {
        mission: 'Expand mobile counseling and case management in Appalachian Tennessee.',
        primary_goal: 'Deploy two additional mobile teams and onboard telehealth triage.',
        funding_amount_needed: '$700,000 for vehicles, clinicians, and remote monitoring.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-bright-trails-youth',
    display_name: 'Bright Trails Youth Services',
    primary_type: 'nonprofit',
    status: 'active',
    tags: ['youth', 'after-school', 'STEM'],
    organization: {
      id: 'org-bright-trails-youth',
      name: 'Bright Trails Youth Services',
      applicant_type: 'nonprofit',
      email: 'info@brighttrails.org',
      phone: '303-555-1188',
      website: 'https://brighttrails.org',
      address: '412 Juniper Avenue',
      city: 'Fort Collins',
      state: 'CO',
      zip: '80521',
      annual_budget: 420000,
      staff_count: 12,
      mission: 'Pair STEM mentors with outdoor leadership for Title I middle schoolers.',
      keywords: ['after-school', 'STEM'],
      focus_areas: ['Youth leadership'],
      program_areas: ['Mobile STEM labs'],
      funding_amount_needed: 'Equip five mobile labs and cover transportation stipends.',
    },
    sections: {
      basic_information: {
        full_name: 'Bright Trails Youth Services',
        email: 'info@brighttrails.org',
        phone: '303-555-1188',
        website: 'https://brighttrails.org',
        address: '412 Juniper Avenue\nFort Collins, CO 80521',
      },
      organization_details: {
        organization_type: 'Youth development nonprofit',
        mission: 'Deliver bilingual STEM mentoring and outdoor leadership.',
      },
      financial_information: {
        financial_need_level: 'Moderate',
        low_income: false,
        notes: 'Bridge financing required while municipal grant renews.',
      },
      government_assistance: {
        medicaid_enrolled: false,
        other_programs: '21st Century Community Learning Centers partner.',
      },
      health_medical: {
        support_needs_level: 'Moderate',
      },
      demographics: {
        african_american: true,
        hispanic_latino: true,
      },
      family_life: {
        single_parent: true,
        homeless: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        nonprofit_employee: true,
        educator: true,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'Fort Collins Title I schools',
      },
      narrative: {
        mission: 'Close STEM opportunity gaps for Black and Latino middle school youth.',
        primary_goal: 'Deploy mobile labs and cover transportation for low-income students.',
        funding_amount_needed: '$180,000 for equipment, coaches, and bus contracts.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-riverbend-veteran-housing',
    display_name: 'Riverbend Veteran Housing Initiative',
    primary_type: 'nonprofit',
    status: 'active',
    tags: ['veterans', 'housing'],
    organization: {
      id: 'org-riverbend-veteran-housing',
      name: 'Riverbend Veteran Housing Initiative',
      applicant_type: 'nonprofit',
      email: 'support@riverbendvets.org',
      phone: '937-555-4411',
      website: 'https://riverbendvets.org',
      address: '88 Veteran Way',
      city: 'Dayton',
      state: 'OH',
      zip: '45402',
      annual_budget: 560000,
      staff_count: 18,
      mission: 'Provide supportive housing and legal aid for unhoused veterans.',
      keywords: ['housing', 'veteran'],
      focus_areas: ['Permanent supportive housing'],
      program_areas: ['HUD-VASH coordination'],
      funding_amount_needed: 'Acquire and renovate two ADA-accessible duplexes.',
    },
    sections: {
      basic_information: {
        full_name: 'Riverbend Veteran Housing Initiative',
        email: 'support@riverbendvets.org',
        phone: '937-555-4411',
        website: 'https://riverbendvets.org',
        address: '88 Veteran Way\nDayton, OH 45402',
      },
      organization_details: {
        organization_type: 'Supportive housing nonprofit',
        mission: 'Stabilize veteran households with wraparound legal and housing support.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
        notes: 'Capital needed before winter rehabs begin.',
      },
      government_assistance: {
        medicaid_enrolled: true,
        ssi_recipient: true,
        section8_housing: true,
      },
      health_medical: {
        support_needs_level: 'High',
        mental_health_condition: true,
      },
      demographics: {
        african_american: true,
      },
      family_life: {
        homeless: true,
      },
      military_service: {
        veteran: true,
        disabled_veteran: true,
      },
      occupation: {
        nonprofit_employee: true,
        public_servant: true,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'Montgomery County (Dayton West Side)',
      },
      narrative: {
        mission: 'Convert vacant duplexes into supportive housing for veterans.',
        primary_goal: 'Close on properties, complete accessibility upgrades, and staff peer teams.',
        funding_amount_needed: '$950,000 for acquisition and renovation.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-harper-family-support',
    display_name: 'Harper Family Support Fund',
    primary_type: 'family',
    status: 'active',
    tags: ['family stability', 'housing'],
    organization: {
      id: 'org-harper-family-support',
      name: 'Harper Family Support Fund',
      applicant_type: 'family',
      email: 'tasha.harper@example.com',
      phone: '901-555-7821',
      website: '',
      address: '278 Willow Crest Drive',
      city: 'Memphis',
      state: 'TN',
      zip: '38109',
      mission: 'Rebuild stability for a single-parent household recovering from surgery.',
      keywords: ['single parent', 'housing'],
      focus_areas: ['Housing stabilization'],
      program_areas: [],
      funding_amount_needed: 'Retire $12,500 in arrears and restart childcare coverage.',
    },
    sections: {
      basic_information: {
        full_name: 'Tasha Harper household',
        email: 'tasha.harper@example.com',
        phone: '901-555-7821',
        address: '278 Willow Crest Drive\nMemphis, TN 38109',
      },
      organization_details: {
        organization_type: 'Household',
        mission: 'Secure childcare and housing while returning to work as a CNA.',
      },
      financial_information: {
        household_income: 32000,
        household_size: 3,
        low_income: true,
        financial_need_level: 'High',
      },
      government_assistance: {
        medicaid_enrolled: true,
        snap_recipient: true,
        tanf_recipient: true,
      },
      health_medical: {
        support_needs_level: 'Moderate',
        mental_health_condition: true,
      },
      demographics: {
        african_american: true,
      },
      family_life: {
        single_parent: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        healthcare_worker: true,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'South Memphis QCT neighborhoods',
      },
      narrative: {
        mission: 'Prevent eviction and rebuild income after medical leave.',
        primary_goal: 'Fund arrears, childcare deposits, and emergency savings.',
        funding_amount_needed: '$12,500 for housing and childcare stabilization.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-northside-robotics',
    display_name: 'Northside Robotics Scholars',
    primary_type: 'high_school_student',
    status: 'active',
    tags: ['STEM', 'first-generation'],
    organization: {
      id: 'org-northside-robotics',
      name: 'Northside Robotics Scholars',
      applicant_type: 'high_school_student',
      email: 'coach.lee@northsidehs.org',
      phone: '502-555-4490',
      address: '800 Ridgeway Avenue',
      city: 'Louisville',
      state: 'KY',
      zip: '40212',
      mission: 'Support first-generation robotics students pursuing engineering pathways.',
      keywords: ['FIRST Robotics', 'engineering'],
      focus_areas: ['STEM education'],
      program_areas: ['Robotics competitions'],
      funding_amount_needed: 'Cover competition travel, certification fees, and laptop upgrades.',
    },
    sections: {
      basic_information: {
        full_name: 'Northside Robotics Scholars',
        email: 'coach.lee@northsidehs.org',
        phone: '502-555-4490',
        address: '800 Ridgeway Avenue\nLouisville, KY 40212',
      },
      organization_details: {
        organization_type: 'Student leadership cohort',
        mission: 'Provide STEM mentorship and scholarship coaching.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
      },
      government_assistance: {
        medicaid_enrolled: true,
        snap_recipient: true,
        section8_housing: true,
      },
      health_medical: {
        support_needs_level: 'Low',
      },
      demographics: {
        african_american: true,
        lgbtq: true,
      },
      family_life: {
        single_parent: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        nonprofit_employee: false,
        public_servant: false,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'West Louisville Promise Zone',
      },
      narrative: {
        mission: 'Help first-generation robotics students enter engineering programs.',
        primary_goal: 'Fund travel, exam costs, and laptops for three scholars.',
        funding_amount_needed: '$32,000 for competition and college access expenses.',
      },
      university_applications: {
        applications: [
          {
            name: 'University of Louisville Speed School of Engineering',
            status: 'interested',
            application_type: 'early_action',
            institution_type: 'public',
            acceptance_rate: 67,
            tuition: 12246,
            fafsa_code: '001999',
            application_fee: 50,
            test_optional: true,
            essay_required: true,
            rec_letters_required: 2,
            application_deadline: '2025-11-15',
            financial_aid_deadline: '2025-12-15',
            interests: ['Mechanical engineering', 'Co-op program'],
            notes: 'Team seeking Speed School scholarships and co-op placement.',
          },
        ],
      },
    },
  },
  {
    id: 'profile-camila-ortiz',
    display_name: 'Camila Ortiz',
    primary_type: 'college_student',
    status: 'active',
    tags: ['nursing', 'latina', 'first-generation'],
    organization: {
      id: 'org-camila-ortiz',
      name: 'Camila Ortiz',
      applicant_type: 'college_student',
      email: 'camila.ortiz@email.com',
      phone: '971-555-3399',
      address: '1140 SE Alder Street Apt 3B',
      city: 'Portland',
      state: 'OR',
      zip: '97214',
      mission: 'Complete BSN program and serve bilingual community health clinics.',
      keywords: ['nursing', 'bilingual'],
      focus_areas: ['Healthcare workforce'],
      program_areas: ['Clinical rotations'],
      funding_amount_needed: 'Cover final-year tuition gap, clinical travel, and NCLEX prep.',
    },
    sections: {
      basic_information: {
        full_name: 'Camila Ortiz',
        email: 'camila.ortiz@email.com',
        phone: '971-555-3399',
        address: '1140 SE Alder Street Apt 3B\nPortland, OR 97214',
      },
      organization_details: {
        organization_type: 'Individual applicant',
        mission: 'Finish BSN and enter community health nursing.',
      },
      financial_information: {
        household_income: 28000,
        household_size: 2,
        low_income: true,
        financial_need_level: 'High',
      },
      government_assistance: {
        medicaid_enrolled: true,
        snap_recipient: true,
      },
      health_medical: {
        support_needs_level: 'Low',
      },
      demographics: {
        hispanic_latino: true,
        immigrant_status: 'permanent_resident',
      },
      family_life: {
        caregiver: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        healthcare_worker: true,
        healthcare_worker_type: 'Certified nursing assistant',
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'Portland community health clinics',
      },
      narrative: {
        mission: 'Provide bilingual nursing care in East Portland clinics.',
        primary_goal: 'Complete BSN and pass NCLEX in 2025.',
        funding_amount_needed: '$24,000 for tuition, travel, and licensing fees.',
      },
      university_applications: {
        applications: [
          {
            name: 'Oregon Health & Science University School of Nursing',
            status: 'planning',
            application_type: 'regular_decision',
            institution_type: 'public',
            acceptance_rate: 34,
            tuition: 17640,
            fafsa_code: '003210',
            application_fee: 75,
            test_optional: true,
            essay_required: true,
            rec_letters_required: 3,
            application_deadline: '2025-01-15',
            financial_aid_deadline: '2025-02-01',
            interests: ['Community health nursing'],
            notes: 'Seeking Nurse Corps scholarship eligibility.',
          },
        ],
      },
    },
  },
  {
    id: 'profile-summit-adaptive-sports',
    display_name: 'Summit Adaptive Sports Alliance',
    primary_type: 'organization',
    status: 'active',
    tags: ['adaptive sports', 'disability inclusion'],
    organization: {
      id: 'org-summit-adaptive-sports',
      name: 'Summit Adaptive Sports Alliance',
      applicant_type: 'organization',
      email: 'info@summitadaptive.org',
      phone: '970-555-2214',
      website: 'https://summitadaptive.org',
      address: '210 Mountain View Circle',
      city: 'Frisco',
      state: 'CO',
      zip: '80443',
      annual_budget: 610000,
      staff_count: 15,
      mission: 'Deliver adaptive outdoor sports and respite for Rocky Mountain families.',
      keywords: ['adaptive sports', 'outdoor recreation'],
      focus_areas: ['Adaptive equipment'],
      program_areas: ['Adaptive ski & ride'],
      funding_amount_needed: 'Purchase adaptive equipment trailer and scholarships.',
    },
    sections: {
      basic_information: {
        full_name: 'Summit Adaptive Sports Alliance',
        email: 'info@summitadaptive.org',
        phone: '970-555-2214',
        website: 'https://summitadaptive.org',
        address: '210 Mountain View Circle\nFrisco, CO 80443',
      },
      organization_details: {
        organization_type: 'Adaptive sports coalition',
        mission: 'Remove barriers so youth with disabilities can access year-round recreation.',
      },
      financial_information: {
        financial_need_level: 'Moderate',
        low_income: false,
      },
      government_assistance: {
        medicaid_enrolled: false,
        other_programs: 'Coordinates IDEA Part B inclusion funds.',
      },
      health_medical: {
        support_needs_level: 'High',
        disability_type: ['Mobility impairments'],
      },
      demographics: {
        hispanic_latino: true,
        native_american: true,
      },
      family_life: {
        caregiver: true,
      },
      military_service: {
        veteran: true,
      },
      occupation: {
        nonprofit_employee: true,
      },
      location_focus: {
        rural_resident: true,
        geographic_focus: 'Rocky Mountain ski counties',
      },
      narrative: {
        mission: 'Expand adaptive sports access across the Rockies.',
        primary_goal: 'Fund equipment trailer, scholarships, and bilingual staff training.',
        funding_amount_needed: '$350,000 for equipment and staffing.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-oak-street-early-learning',
    display_name: 'Oak Street Early Learning Center',
    primary_type: 'nonprofit',
    status: 'active',
    tags: ['early childhood', 'dual language'],
    organization: {
      id: 'org-oak-street-early-learning',
      name: 'Oak Street Early Learning Center',
      applicant_type: 'nonprofit',
      email: 'director@oakstreetelc.org',
      phone: '414-555-2016',
      website: 'https://oakstreetelc.org',
      address: '932 Oak Street',
      city: 'Milwaukee',
      state: 'WI',
      zip: '53204',
      annual_budget: 780000,
      staff_count: 32,
      mission: 'Provide bilingual early learning and wraparound family services.',
      keywords: ['Head Start', 'dual language'],
      focus_areas: ['Pre-K expansion'],
      program_areas: ['Family resource center'],
      funding_amount_needed: 'Renovate classrooms and expand infant care slots.',
    },
    sections: {
      basic_information: {
        full_name: 'Oak Street Early Learning Center',
        email: 'director@oakstreetelc.org',
        phone: '414-555-2016',
        website: 'https://oakstreetelc.org',
        address: '932 Oak Street\nMilwaukee, WI 53204',
      },
      organization_details: {
        organization_type: 'Early childhood education center',
        mission: 'Expand dual-language infant care with trauma-informed supports.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
      },
      government_assistance: {
        medicaid_enrolled: false,
        other_programs: 'Head Start delegate and city childcare stabilization grant.',
      },
      health_medical: {
        support_needs_level: 'Moderate',
        mental_health_condition: true,
      },
      demographics: {
        african_american: true,
        hispanic_latino: true,
      },
      family_life: {
        single_parent: true,
        homeless: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        nonprofit_employee: true,
        public_servant: true,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'Milwaukee Southside Promise Zone',
      },
      narrative: {
        mission: 'Expand dual-language early learning for low-income families.',
        primary_goal: 'Renovate unused classrooms and purchase infant equipment.',
        funding_amount_needed: '$410,000 for renovations and training.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-sierra-tribal-artisans',
    display_name: 'Sierra Tribal Artisans Collaborative',
    primary_type: 'small_business',
    status: 'active',
    tags: ['tribal enterprise', 'artisan training'],
    organization: {
      id: 'org-sierra-tribal-artisans',
      name: 'Sierra Tribal Artisans Collaborative',
      applicant_type: 'small_business',
      email: 'info@sierratribalarts.com',
      phone: '775-555-7022',
      website: 'https://sierratribalarts.com',
      address: '65 Eagle Feather Drive',
      city: 'Schurz',
      state: 'NV',
      zip: '89427',
      annual_budget: 210000,
      staff_count: 9,
      mission: 'Grow artisan training and e-commerce for Walker River Paiute creatives.',
      keywords: ['tribal enterprise', 'artisan'],
      focus_areas: ['Rural economic development'],
      program_areas: ['Artisan incubator'],
      funding_amount_needed: 'Upgrade fabrication studio and launch national partnerships.',
    },
    sections: {
      basic_information: {
        full_name: 'Sierra Tribal Artisans Collaborative',
        email: 'info@sierratribalarts.com',
        phone: '775-555-7022',
        website: 'https://sierratribalarts.com',
        address: '65 Eagle Feather Drive\nSchurz, NV 89427',
      },
      organization_details: {
        organization_type: 'Tribal artisan cooperative',
        mission: 'Create economic pathways for Walker River Paiute artisans.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
      },
      government_assistance: {
        medicaid_enrolled: true,
        snap_recipient: true,
      },
      health_medical: {
        support_needs_level: 'Moderate',
        disability_type: ['Mobility limitations'],
      },
      demographics: {
        native_american: true,
      },
      family_life: {
        caregiver: true,
      },
      military_service: {
        veteran: true,
      },
      occupation: {
        small_business_owner: true,
      },
      location_focus: {
        rural_resident: true,
        geographic_focus: 'Walker River Paiute Reservation',
      },
      narrative: {
        mission: 'Scale tribal artisan enterprises and preserve cultural design heritage.',
        primary_goal: 'Upgrade fabrication studio and expand e-commerce logistics.',
        funding_amount_needed: '$265,000 for equipment, marketing, and logistics.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-greenline-food-coop',
    display_name: 'Greenline Food Cooperative',
    primary_type: 'small_business',
    status: 'active',
    tags: ['food access', 'cooperative'],
    organization: {
      id: 'org-greenline-food-coop',
      name: 'Greenline Food Cooperative',
      applicant_type: 'small_business',
      email: 'hello@greenlinecoop.org',
      phone: '313-555-9087',
      website: 'https://greenlinecoop.org',
      address: '1450 Elmwood Street',
      city: 'Detroit',
      state: 'MI',
      zip: '48207',
      annual_budget: 490000,
      staff_count: 22,
      mission: 'Provide affordable groceries and cooperative jobs in a Detroit food desert.',
      keywords: ['food access', 'cooperative'],
      focus_areas: ['Healthy food retail'],
      program_areas: ['Mobile market'],
      funding_amount_needed: 'Renovate expansion space and add cold storage.',
    },
    sections: {
      basic_information: {
        full_name: 'Greenline Food Cooperative',
        email: 'hello@greenlinecoop.org',
        phone: '313-555-9087',
        website: 'https://greenlinecoop.org',
        address: '1450 Elmwood Street\nDetroit, MI 48207',
      },
      organization_details: {
        organization_type: 'Worker-owned grocery cooperative',
        mission: 'Expand cooperative grocery access and mobile markets on Detroit\'s east side.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
      },
      government_assistance: {
        snap_recipient: true,
        other_programs: 'Double Up Food Bucks incentive partner.',
      },
      health_medical: {
        support_needs_level: 'Moderate',
        chronic_illness: true,
      },
      demographics: {
        african_american: true,
        lgbtq: true,
      },
      family_life: {
        single_parent: true,
      },
      military_service: {
        veteran: false,
      },
      occupation: {
        small_business_owner: true,
      },
      location_focus: {
        urban_underserved: true,
        geographic_focus: 'Detroit east side Opportunity Zone',
      },
      narrative: {
        mission: 'Expand equitable grocery access and worker ownership in Detroit.',
        primary_goal: 'Renovate expansion space, add cold storage, and grow mobile routes.',
        funding_amount_needed: '$520,000 for renovations, equipment, and vehicles.',
      },
      university_applications: { applications: [] },
    },
  },
  {
    id: 'profile-lakeside-recovery-alliance',
    display_name: 'Lakeside Recovery Alliance',
    primary_type: 'medical_assistance',
    status: 'active',
    tags: ['behavioral health', 'recovery', 'peer support'],
    organization: {
      id: 'org-lakeside-recovery-alliance',
      name: 'Lakeside Recovery Alliance',
      applicant_type: 'medical_assistance',
      email: 'contact@lakesiderecovery.org',
      phone: '218-555-6742',
      website: 'https://lakesiderecovery.org',
      address: '401 Lake Street',
      city: 'Duluth',
      state: 'MN',
      zip: '55802',
      annual_budget: 360000,
      staff_count: 14,
      mission: 'Provide peer recovery coaching, MAT navigation, and family support in frontier counties.',
      keywords: ['recovery', 'MAT'],
      focus_areas: ['Behavioral health'],
      program_areas: ['Mobile recovery coaches'],
      funding_amount_needed: 'Expand mobile recovery teams and open a telehealth hub.',
    },
    sections: {
      basic_information: {
        full_name: 'Lakeside Recovery Alliance',
        email: 'contact@lakesiderecovery.org',
        phone: '218-555-6742',
        website: 'https://lakesiderecovery.org',
        address: '401 Lake Street\nDuluth, MN 55802',
      },
      organization_details: {
        organization_type: 'Recovery community organization',
        mission: 'Deliver peer-led recovery navigation across northern Minnesota.',
      },
      financial_information: {
        financial_need_level: 'High',
        low_income: true,
        notes: 'Operating on thin reserves as state opioid response contracts renew.',
      },
      government_assistance: {
        medicaid_enrolled: true,
        other_programs: 'Minnesota State Opioid Response grant partner.',
      },
      health_medical: {
        support_needs_level: 'High',
        mental_health_condition: true,
      },
      demographics: {
        hispanic_latino: true,
        native_american: true,
        lgbtq: true,
      },
      family_life: {
        caregiver: true,
        homeless: true,
      },
      military_service: {
        veteran: true,
      },
      occupation: {
        nonprofit_employee: true,
        public_servant: true,
      },
      location_focus: {
        rural_resident: true,
        geographic_focus: 'Lake Superior frontier counties and tribal communities',
      },
      narrative: {
        mission: 'Reduce overdose deaths with peer-led supports.',
        primary_goal: 'Scale mobile coaching, launch telehealth hub, and expand family wraparound services.',
        funding_amount_needed: '$315,000 for staffing, telehealth infrastructure, and housing stipends.',
      },
      university_applications: { applications: [] },
    },
  },
]
