// crawler-os/sourceRegistry.js
//
// THE data-driven registry of real funding sources. One row per source. The
// planner reads this; adapters are matched to rows by source_id. Every URL here
// is a real, public endpoint. Growing the funding universe = adding rows here +
// a thin adapter, never new bespoke crawler logic.
//
// Pure data. No I/O.

import { TRUST_TIER, OPPORTUNITY_KIND } from './contract.js';

/**
 * Source row fields:
 *  - source_id        stable slug (also the adapter key)
 *  - name             human label
 *  - source_type      'api' | 'html' | 'directory' | 'rss'
 *  - trust_tier       TRUST_TIER.*
 *  - base_url         real public base URL
 *  - directory        true if this is a locator/list, not a direct-apply source
 *  - loan_allowed     does this source ever surface loans (gated again per profile)
 *  - cost_share_allowed
 *  - applicant_types  buckets this source serves ('*' = broad)
 *  - need_categories  needs this source covers ('*' = broad)
 *  - geography        { national, states }
 *  - default_kinds    the kind(s) candidates from this source default to
 *  - crawler_method   'api'|'html'|'rss'|'pdf'
 *  - requires_env     env keys required (honest skip if absent), or []
 *  - refresh_frequency_days  scheduler cadence hint
 *  - priority_score   planner tie-breaker
 */
export const SOURCES = Object.freeze([
  {
    source_id: 'grants_gov',
    name: 'Grants.gov (U.S. federal grants)',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://www.grants.gov',
    directory: false,
    loan_allowed: false,
    cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'vfd', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECT_GRANT],
    crawler_method: 'api',
    requires_env: [],
    refresh_frequency_days: 1,
    priority_score: 100,
  },
  {
    source_id: 'sam_gov',
    name: 'SAM.gov assistance listings',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://sam.gov',
    directory: false,
    loan_allowed: true, // CFDA includes loan programs; gated per profile downstream
    cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api',
    // Keyless: the sam.gov assistance-listings search needs no API key (the old
    // api.sam.gov host that required SAM_GOV_API_KEY was retired — see samGovAdapter.js).
    requires_env: [],
    refresh_frequency_days: 7,
    priority_score: 90,
  },
  {
    source_id: 'cof_locator',
    name: 'Council on Foundations — Community Foundation Locator',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.cof.org',
    directory: true,
    loan_allowed: false,
    cost_share_allowed: false,
    applicant_types: ['*'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html',
    requires_env: [],
    refresh_frequency_days: 30,
    priority_score: 40,
  },
  {
    source_id: 'benefits_gov',
    name: 'Benefits.gov (federal benefit finder)',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.benefits.gov',
    directory: true,
    loan_allowed: false,
    cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'education', 'veterans', 'caregiving', 'survivor_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html',
    requires_env: [],
    refresh_frequency_days: 14,
    priority_score: 60,
  },
  // --- Registry rows below have no adapter yet: the planner will SELECT them and
  //     the pipeline records an honest SKIPPED(no_adapter), never fakes results.
  //     Each becomes live by adding a thin createBaseAdapter() config. ---
  {
    source_id: 'usda_rd',
    name: 'USDA Rural Development programs',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.rd.usda.gov',
    directory: false, loan_allowed: true, cost_share_allowed: true,
    applicant_types: ['farm', 'government', 'business', 'vfd'],
    need_categories: ['capital', 'equipment', 'operations', 'energy'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 55,
  },
  {
    source_id: 'fema_afg',
    name: 'FEMA Assistance to Firefighters Grants',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fema.gov',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['vfd', 'government'],
    need_categories: ['equipment', 'emergency', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECT_GRANT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 65,
  },
  {
    source_id: 'studentaid_gov',
    name: 'Federal Student Aid (studentaid.gov)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  // (CareerOneStop Scholarship Finder was removed here on 2026-06-23: DOL
  // retired the scholarship Web API — their 21 live services include none, and
  // scholarship* endpoints 404 while occupation returns 200 with the same token.
  // Individual scholarships are sourced by the Brave+LLM scholarshipWebDiscovery
  // service instead. If DOL reinstates it, re-add a row + a thin adapter.)
  //
  // --- Net-new key-free federal lanes (2026-06-24) ---------------------------
  {
    source_id: 'federal_register',
    name: 'Federal Register — funding notices (NOFO/NOFA)',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://www.federalregister.gov',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    // Federal NOFOs are institutional (agencies fund orgs/govts), so this lane
    // is gated OUT for individuals/students — the same precision as grants.gov.
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'vfd', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api', requires_env: [], refresh_frequency_days: 1, priority_score: 80,
  },
  {
    source_id: 'nih_guide',
    name: 'NIH Guide for Grants & Contracts (funding opportunities)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://grants.nih.gov/grants/guide/newsfeed/fundingopps.xml',
    feed_url: 'https://grants.nih.gov/grants/guide/newsfeed/fundingopps.xml',
    sponsor_name: 'U.S. National Institutes of Health',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business'],
    // Research/health-leaning (NOT '*'): only profiles whose needs overlap (or
    // have no specific needs) pull NIH notices, so a fire dept needing turnout
    // gear isn't shown research R01s. The match engine still scores relevance.
    need_categories: ['medical', 'programs', 'technology', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 7, priority_score: 70,
  },
  {
    source_id: 'united_way_211',
    name: '211 local assistance directory',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.211.org/get-help',
    sponsor_name: '211',
    resource_title: '211 local assistance finder',
    resource_summary: 'Connects people to local help for food, housing, utilities, health care, transportation, legal aid, and crisis needs. This is a directory, not a direct grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'emergency', 'legal', 'caregiving', 'survivor_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 75,
  },
  {
    source_id: 'donorschoose',
    name: 'DonorsChoose classroom funding',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.donorschoose.org/teachers',
    sponsor_name: 'DonorsChoose',
    resource_title: 'DonorsChoose teacher project funding',
    resource_summary: 'Teacher-facing classroom project funding platform for supplies, books, technology, and student materials. GrantFlow treats this as a portal/directory, not a guaranteed award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['teacher', 'school'],
    need_categories: ['education', 'equipment', 'technology'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    source_id: 'cancer_care',
    name: 'CancerCare financial assistance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.cancercare.org/financial_assistance',
    sponsor_name: 'CancerCare',
    resource_title: 'CancerCare financial assistance',
    resource_summary: 'Financial and practical-support assistance information for people affected by cancer. Eligibility and available funds vary, so this is surfaced for review rather than promised as an award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['cancer_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'ssa_survivors',
    name: 'Social Security survivors benefits',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.ssa.gov/survivor',
    sponsor_name: 'Social Security Administration',
    resource_title: 'Social Security survivors benefits',
    resource_summary: 'Official Social Security survivor-benefits information for eligible surviving spouses, children, and families. This is a benefits lane, not a grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['survivor_benefits', 'housing', 'food', 'medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'dol_black_lung_benefits',
    name: 'DOL Black Lung Program',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dol.gov/agencies/owcp/dcmwc/filing_guide_survivor',
    sponsor_name: 'U.S. Department of Labor',
    resource_title: 'Black Lung Program benefits',
    resource_summary: 'Official Department of Labor Black Lung Program information for eligible coal miners and surviving family members. GrantFlow treats this as benefit guidance, not an open grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['black_lung_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  {
    source_id: 'alzheimers_gov_services',
    name: 'Alzheimers.gov local services',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.alzheimers.gov/life-with-dementia/find-local-services',
    sponsor_name: 'Alzheimers.gov',
    resource_title: 'Dementia local services finder',
    resource_summary: 'Official federal dementia resource for finding local services, support, and care resources for people living with dementia and their caregivers.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['dementia_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  {
    source_id: 'kynect_benefits',
    name: 'Kentucky kynect benefits',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://kynect.ky.gov/benefits/s/?language=en_US',
    sponsor_name: 'Commonwealth of Kentucky',
    resource_title: 'Kentucky kynect benefits',
    resource_summary: 'Official Kentucky benefits portal for programs such as health coverage, food assistance, child care, and other household supports.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'caregiving', 'survivor_benefits'],
    geography: { national: false, states: ['KY'] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 78,
  },
  {
    source_id: 'ana_grants',
    name: 'Administration for Native Americans grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.acf.hhs.gov/ana/grants',
    sponsor_name: 'Administration for Native Americans',
    resource_title: 'Administration for Native Americans grants',
    resource_summary: 'Official Administration for Native Americans grants resource for tribal governments, Native nonprofits, and Native communities.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['tribal', 'government', 'nonprofit'],
    need_categories: ['capital', 'operations', 'programs', 'technology', 'public_safety', 'agriculture', 'recreation', 'energy'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'sba_grants',
    name: 'SBA grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/funding-programs/grants',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'SBA grants',
    resource_summary: 'Official SBA grants page. SBA grants are limited and are not ordinary practice-startup money; loans are not surfaced here unless a profile explicitly allows loan products elsewhere.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['business', 'farm'],
    need_categories: ['capital', 'operations', 'technology', 'agriculture', 'legal', 'startup', 'equipment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 62,
  },
  {
    source_id: 'sba_veteran_business',
    name: 'SBA veteran-owned business resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/business-guide/grow-your-business/veteran-owned-businesses',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'SBA veteran-owned business resources',
    resource_summary: 'Official SBA resource page for veterans, service members, and military spouses starting or growing a business. This is resource guidance, not guaranteed funding.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['veteran', 'business', 'individual'],
    need_categories: ['veteran_startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'sba_vboc',
    name: 'SBA Veterans Business Outreach Centers',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/local-assistance/resource-partners/veterans-business-outreach-centers-vboc',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'Veterans Business Outreach Center program',
    resource_summary: 'Official SBA VBOC program resource for veteran and military-community entrepreneurs seeking business training, counseling, and startup support.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['veteran', 'business', 'individual'],
    need_categories: ['veteran_startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 71,
  },
  {
    source_id: 'wv_sbdc_funding',
    name: 'West Virginia SBDC funding resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://wvsbdc.com/services/funding/',
    sponsor_name: 'West Virginia Small Business Development Center',
    resource_title: 'WV SBDC funding resources',
    resource_summary: 'West Virginia Small Business Development Center funding-resource page for small business owners and startup founders. Loan products still remain gated by user preference.',
    directory: true, loan_allowed: true, cost_share_allowed: false,
    applicant_types: ['business', 'individual', 'veteran'],
    need_categories: ['startup', 'capital', 'operations', 'equipment'],
    geography: { national: false, states: ['WV'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 73,
  },
  {
    source_id: 'wv_business_funding_resources',
    name: 'West Virginia business funding resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://sos.wv.gov/business/general-information/funding-grant-resources',
    sponsor_name: 'West Virginia Secretary of State',
    resource_title: 'West Virginia funding and grant resources',
    resource_summary: 'Official West Virginia business funding-resource page listing organizations that offer funding, loans, grants, and guidance for West Virginia businesses. Loan products remain gated by user preference.',
    directory: true, loan_allowed: true, cost_share_allowed: false,
    applicant_types: ['business', 'individual', 'veteran'],
    need_categories: ['startup', 'capital', 'operations', 'equipment'],
    geography: { national: false, states: ['WV'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'lsc_grants',
    name: 'Legal Services Corporation grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.lsc.gov/grants',
    sponsor_name: 'Legal Services Corporation',
    resource_title: 'Legal Services Corporation grants',
    resource_summary: 'Official LSC grant information for civil legal aid organizations. This is for eligible legal-services organizations, not a general private law-practice grant.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'government'],
    need_categories: ['legal', 'programs', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 58,
  },
  {
    source_id: 'oregon_parks_rec_grants',
    name: 'Oregon Parks and Recreation Department grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.oregon.gov/oprd/GRA/Pages/GRA-overview.aspx',
    sponsor_name: 'Oregon Parks and Recreation Department',
    resource_title: 'Oregon parks and recreation grant programs',
    resource_summary: 'Official Oregon parks and recreation grants overview for public recreation, trails, parks, heritage, and local government projects.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'nonprofit'],
    need_categories: ['recreation', 'capital', 'equipment', 'programs'],
    geography: { national: false, states: ['OR'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  {
    source_id: 'dhs_grants',
    name: 'DHS grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dhs.gov/dhs-grants',
    sponsor_name: 'U.S. Department of Homeland Security',
    resource_title: 'DHS grants',
    resource_summary: 'Official DHS grants page for preparedness, security, emergency management, and homeland-security programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'vfd', 'law_enforcement'],
    need_categories: ['public_safety', 'emergency', 'equipment', 'technology', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 73,
  },
  {
    source_id: 'doj_grants',
    name: 'Department of Justice grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.justice.gov/grants',
    sponsor_name: 'U.S. Department of Justice',
    resource_title: 'Department of Justice grants',
    resource_summary: 'Official DOJ grants page for public safety, legal services, violence prevention, victim services, and justice programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'law_enforcement'],
    need_categories: ['public_safety', 'legal', 'programs', 'technology'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 71,
  },
  {
    source_id: 'cops_grants',
    name: 'COPS Office grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://cops.usdoj.gov/grants',
    sponsor_name: 'U.S. Department of Justice COPS Office',
    resource_title: 'COPS Office grants',
    resource_summary: 'Official COPS Office grants page for community policing, law-enforcement hiring, equipment, training, and public-safety programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'law_enforcement'],
    need_categories: ['public_safety', 'equipment', 'technology', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 70,
  },
  {
    source_id: 'fec_candidate_resources',
    name: 'FEC candidate and committee resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fec.gov/help-candidates-and-committees/',
    sponsor_name: 'Federal Election Commission',
    resource_title: 'FEC candidate and committee resources',
    resource_summary: 'Official federal campaign-finance resource. This is compliance/funding-process guidance, not a grant or award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['candidate'],
    need_categories: ['campaign', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 64,
  },
  {
    source_id: 'pa_campaign_finance',
    name: 'Pennsylvania campaign finance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.pa.gov/agencies/dos/programs/voting-and-elections/campaign-finance',
    sponsor_name: 'Pennsylvania Department of State',
    resource_title: 'Pennsylvania campaign finance resources',
    resource_summary: 'Official Pennsylvania campaign-finance resource for candidates and committees. This is state compliance/funding-process guidance, not a grant or guaranteed funding source.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['candidate'],
    need_categories: ['campaign', 'operations'],
    geography: { national: false, states: ['PA'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
]);

const BY_ID = Object.freeze(Object.fromEntries(SOURCES.map((s) => [s.source_id, s])));

export function allSources() { return SOURCES.map((s) => ({ ...s })); }
export function getSource(id) { const s = BY_ID[id]; return s ? { ...s } : null; }
export function sourceIds() { return SOURCES.map((s) => s.source_id); }

export default { SOURCES, allSources, getSource, sourceIds };
