// crawler-os/sourceRegistry.js
//
// THE data-driven registry of real funding sources. One row per source. The
// planner reads this; adapters are matched to rows by source_id. Every URL here
// is a real, public endpoint. Growing the funding universe = adding rows here +
// a thin adapter, never new bespoke crawler logic.
//
// Pure data. No I/O.

import { TRUST_TIER, OPPORTUNITY_KIND } from './contract.js';
// Amy-managed additive coverage overrides (broaden an existing source's
// need_categories/applicant_types). Additive-only + reversible; lives inside
// the OS so the package stays self-contained. See ./coverageOverrides.js.
import { mergeSourceCoverage } from './coverageOverrides.js';

/**
 * Source row fields:
 *  - source_id        stable slug (also the adapter key)
 *  - name             human label
 *  - source_type      'api' | 'html' | 'directory' | 'rss'
 *  - trust_tier       TRUST_TIER.*
 *  - base_url         real public base URL
 *  - directory        true if this is a locator/list, not a direct-apply source
 *  - loan_allowed     does this source ever surface loans (gated again per profile)
 *  - cost_share_allowed
 *  - applicant_types  buckets this source serves ('*' = broad)
 *  - need_categories  needs this source covers ('*' = broad)
 *  - geography        { national, states }
 *  - default_kinds    the kind(s) candidates from this source default to
 *  - crawler_method   'api'|'html'|'rss'|'pdf'
 *  - requires_env     env keys required (honest skip if absent), or []
 *  - refresh_frequency_days  scheduler cadence hint
 *  - priority_score   planner tie-breaker
 */
export const SOURCES = Object.freeze([
  {
    source_id: 'grants_gov',
    name: 'Grants.gov (U.S. federal grants)',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://www.grants.gov',
    directory: false,
    loan_allowed: false,
    cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'vfd', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECT_GRANT],
    crawler_method: 'api',
    requires_env: [],
    refresh_frequency_days: 1,
    priority_score: 100,
  },
  {
    source_id: 'sam_gov',
    name: 'SAM.gov assistance listings',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://sam.gov',
    directory: false,
    loan_allowed: true, // CFDA includes loan programs; gated per profile downstream
    cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api',
    // Keyless: the sam.gov assistance-listings search needs no API key (the old
    // api.sam.gov host that required SAM_GOV_API_KEY was retired — see samGovAdapter.js).
    requires_env: [],
    refresh_frequency_days: 7,
    priority_score: 90,
  },
  {
    source_id: 'sbir_gov',
    name: 'SBIR.gov (Small Business Innovation Research / STTR solicitations)',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://www.sbir.gov',
    directory: false,
    loan_allowed: false,
    cost_share_allowed: false,
    // SBIR/STTR is exclusively for small for-profit businesses; nonprofit is
    // included only because generic research orgs derive both buckets — the
    // research_only gate below is the real precision control.
    applicant_types: ['business', 'nonprofit'],
    need_categories: ['*'],
    // ONLY selected for research-capable orgs (thesis.is_research_org) — the
    // planner's research_only gate. A food pantry never searches solicitations.
    research_only: true,
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api',
    // Public API, no key. NOTE (2026-07-06): api.www.sbir.gov currently
    // returns "The SBIR Public API is not available at this time" service-wide;
    // the adapter reports an honest PARSE_ERROR until it comes back.
    requires_env: [],
    refresh_frequency_days: 3,
    priority_score: 95,
  },
  {
    source_id: 'cof_locator',
    name: 'Council on Foundations — Community Foundation Locator',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.cof.org',
    directory: true,
    loan_allowed: false,
    cost_share_allowed: false,
    applicant_types: ['*'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html',
    requires_env: [],
    refresh_frequency_days: 30,
    priority_score: 40,
  },
  {
    source_id: 'benefits_gov',
    name: 'Benefits.gov (federal benefit finder)',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.benefits.gov',
    directory: true,
    loan_allowed: false,
    cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'active_duty', 'guard_reserve', 'transitioning_service_member', 'military_spouse', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'education', 'veterans', 'active_duty_support', 'military_transition', 'military_spouse_support', 'caregiving', 'survivor_benefits'],
    geography: { national: true, states: [] },
    // The adapter emits one DIRECTORY candidate for the benefit finder, not
    // individual apply-now benefit rows. Keep the registry honest.
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html',
    requires_env: [],
    refresh_frequency_days: 14,
    priority_score: 60,
  },
  {
    source_id: 'community_action',
    name: 'Community Action Partnership agency finder',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://communityactionpartnership.com/find-a-cap/',
    sponsor_name: 'Community Action Partnership',
    resource_title: 'Community Action agency finder',
    resource_summary: 'Directory of local Community Action agencies for housing, utilities, food, transportation, childcare, and household support referrals.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran', 'active_duty', 'guard_reserve', 'military_spouse'],
    need_categories: ['housing', 'food', 'energy', 'childcare', 'transportation', 'medical', 'emergency'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  {
    source_id: 'feeding_america',
    name: 'Feeding America food bank locator',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.feedingamerica.org/find-your-local-foodbank',
    sponsor_name: 'Feeding America',
    resource_title: 'Local food bank locator',
    resource_summary: 'Directory for finding local food banks and hunger-relief networks. This is a directory/referral lane, not a direct cash grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran', 'nonprofit', 'church', 'ministry'],
    need_categories: ['food', 'school_nutrition'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 63,
  },
  {
    source_id: 'hrsa_health_centers',
    name: 'HRSA Find a Health Center',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://findahealthcenter.hrsa.gov',
    sponsor_name: 'Health Resources and Services Administration',
    resource_title: 'HRSA Find a Health Center',
    resource_summary: 'Official locator for HRSA-funded health centers that may provide care regardless of ability to pay.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran', 'active_duty', 'guard_reserve'],
    need_categories: ['medical', 'disability', 'medical_bills', 'medication', 'mental_health', 'substance_recovery'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 69,
  },
  {
    source_id: 'liheap',
    name: 'LIHEAP energy assistance',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.acf.hhs.gov/ocs/programs/liheap',
    sponsor_name: 'Administration for Children and Families',
    resource_title: 'Low Income Home Energy Assistance Program',
    resource_summary: 'Official LIHEAP program information for eligible households needing energy, heating, cooling, or utility-bill assistance.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran'],
    need_categories: ['energy', 'housing'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    source_id: 'snap',
    name: 'USDA SNAP state directory',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fns.usda.gov/snap/state-directory',
    sponsor_name: 'U.S. Department of Agriculture',
    resource_title: 'SNAP state directory',
    resource_summary: 'Official SNAP state directory for food-assistance application portals and local program information.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran'],
    need_categories: ['food'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 67,
  },
  {
    source_id: 'medicaid',
    name: 'Medicaid and CHIP',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.medicaid.gov',
    sponsor_name: 'Centers for Medicare & Medicaid Services',
    resource_title: 'Medicaid and CHIP',
    resource_summary: 'Official Medicaid and CHIP program information for health coverage and medical support.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran'],
    need_categories: ['medical', 'disability', 'medical_bills', 'medication'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 67,
  },
  {
    // TennCare ECF CHOICES — Tennessee's Medicaid HCBS waiver (employment and
    // community-living supports for people with intellectual/developmental
    // disabilities + Essential Family Supports for family caregivers). Ported
    // from the legacy ecfBenefitsCrawler on 2026-07-07: the legacy crawler was
    // never registered here, so after the crawler-os cutover the ECF lane was
    // structurally uncrawlable — actual ECF CHOICES members (the Gilbert/Kim
    // class) never had their own program crawled. NOTE: tn.gov intermittently
    // ECONNRESETs automated fetchers; the adapter degrades honestly
    // (FETCH_ERROR), never fabricates.
    source_id: 'tn_ecf_choices',
    name: 'TennCare Employment and Community First CHOICES (ECF CHOICES)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.tn.gov/tenncare/long-term-services-supports/employment-and-community-first-choices.html',
    sponsor_name: 'TennCare',
    resource_title: 'Employment and Community First CHOICES (ECF CHOICES)',
    resource_summary: 'Official TennCare ECF CHOICES program page: employment and independent-community-living supports for Tennesseans with intellectual or developmental disabilities, including Essential Family Supports for family caregivers.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'disabled', 'caregiver'],
    need_categories: ['disability', 'healthcare', 'medical', 'employment', 'caregiving'],
    geography: { national: false, states: ['TN'] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 78,
  },
  {
    // Every state's Medicaid HCBS waiver universe (the legacy
    // stateWaiverBenefitsCrawler's generic scope): the medicaid.gov HCBS index
    // is the authoritative national locator for state waiver programs — each
    // state's ECF-CHOICES-equivalent. An honest DIRECTORY, so a waiver-family
    // profile outside TN still reaches its own state's program.
    source_id: 'state_hcbs_waivers',
    name: 'Medicaid Home & Community-Based Services (HCBS) waivers by state',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.medicaid.gov/medicaid/home-community-based-services/index.html',
    sponsor_name: 'Centers for Medicare & Medicaid Services',
    resource_title: 'Medicaid HCBS waiver programs (state directory)',
    resource_summary: 'Official CMS index of Home and Community-Based Services waiver programs — the entry point for finding your state\'s Medicaid waiver (employment supports, community living, respite, and caregiver services).',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'senior', 'veteran', 'disabled', 'caregiver'],
    need_categories: ['disability', 'healthcare', 'medical', 'caregiving', 'aging'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 69,
  },
  {
    // SSA disability benefits (SSDI/SSI) — the federal branch of the legacy ECF
    // crawler's individual sources. NOTE: ssa.gov intermittently 403s automated
    // fetchers (seen in CI); as a directory-kind locator the honest row survives
    // a failed fetch (link_unverified ≠ dead) while the run records fetch_error.
    source_id: 'ssa_disability',
    name: 'Social Security disability benefits (SSDI / SSI)',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.ssa.gov/disability',
    sponsor_name: 'Social Security Administration',
    resource_title: 'Social Security disability benefits (SSDI/SSI)',
    resource_summary: 'Official Social Security disability-benefits information and application entry point: SSDI for workers with a qualifying disability and SSI for people with limited income and resources. This is a benefits lane, not a grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'disabled'],
    need_categories: ['disability', 'medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    // Seniors + their caregivers: the Eldercare Locator connects older adults to
    // their local Area Agency on Aging (meals, transportation, in-home support,
    // caregiver respite). An authoritative national locator — surfaced as an
    // honest DIRECTORY so it reaches senior/caregiver profiles the grant sources miss.
    source_id: 'area_agency_on_aging',
    name: 'Area Agencies on Aging (Eldercare Locator)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://eldercare.acl.gov',
    sponsor_name: 'Administration for Community Living',
    resource_title: 'Area Agency on Aging & Eldercare Locator',
    resource_summary: 'Find your local Area Agency on Aging for senior services: meals, transportation, in-home care, benefits counseling, and caregiver respite support.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'senior', 'caregiver'],
    need_categories: ['aging', 'senior', 'housing', 'food', 'medical', 'caregiving', 'transportation'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  {
    // People with disabilities: state Vocational Rehabilitation agencies fund
    // assistive technology, job training, and employment support. Reachable only
    // by the state agency locator, so individuals never find them via grant search.
    source_id: 'state_vocational_rehab',
    name: 'State Vocational Rehabilitation agencies',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://rsa.ed.gov/about/states',
    sponsor_name: 'Rehabilitation Services Administration',
    resource_title: 'State Vocational Rehabilitation (disability employment & assistive tech)',
    resource_summary: 'State VR agencies help people with disabilities get assistive technology, job training, and employment support. Find your state agency to apply.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'disabled'],
    need_categories: ['disability', 'employment', 'assistive_technology', 'education', 'equipment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  {
    // Universal local safety net: 211 connects anyone to nearby help for rent,
    // utilities, food, and emergencies. The single best locator for a low-income
    // individual (works even for a sparse profile), so it is a national DIRECTORY.
    source_id: 'community_211',
    name: '211 local community resources',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.211.org',
    sponsor_name: 'United Way / 211',
    resource_title: '211 - Local help with rent, utilities, food & emergencies',
    resource_summary: 'Dial 211 or search 211.org to connect with local programs for rent and utility assistance, food, healthcare, and emergency needs in your area.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'senior', 'veteran', 'caregiver'],
    need_categories: ['housing', 'energy', 'utility', 'food', 'emergency', 'medical', 'basic_needs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 67,
  },
  {
    source_id: 'pell_grant',
    name: 'Federal Pell Grant',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov/understand-aid/types/grants/pell',
    sponsor_name: 'Federal Student Aid',
    resource_title: 'Federal Pell Grant',
    resource_summary: 'Official Federal Student Aid Pell Grant page. Eligibility is determined through FAFSA and school financial-aid processing.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education', 'scholarship', 'fafsa', 'pell', 'tuition'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 71,
  },
  // --- Sibling federal need-based student aid (the rest of the "federal grant"
  //     family beyond Pell). Real official studentaid.gov program pages, modeled
  //     exactly like pell_grant so a student/family profile surfaces the FULL set
  //     of federal aid — not just the Pell Grant. Each flows through the same
  //     reality gate + match engine; nothing is fabricated. ---
  {
    source_id: 'fseog',
    name: 'Federal Supplemental Educational Opportunity Grant (FSEOG)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov/understand-aid/types/grants/fseog',
    sponsor_name: 'Federal Student Aid',
    resource_title: 'Federal Supplemental Educational Opportunity Grant (FSEOG)',
    resource_summary: 'Official Federal Student Aid FSEOG page. Need-based grant for undergraduates with exceptional financial need (priority to Pell recipients); awarded by participating schools. Does not need to be repaid.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education', 'scholarship', 'fafsa', 'pell', 'tuition'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  {
    source_id: 'federal_work_study',
    name: 'Federal Work-Study',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov/understand-aid/types/work-study',
    sponsor_name: 'Federal Student Aid',
    resource_title: 'Federal Work-Study',
    resource_summary: 'Official Federal Student Aid Work-Study page. Part-time jobs for undergraduate and graduate students with financial need to help pay education expenses; awarded by participating schools via the FAFSA.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education', 'scholarship', 'fafsa', 'tuition', 'employment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 69,
  },
  {
    source_id: 'teach_grant',
    name: 'TEACH Grant',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov/understand-aid/types/grants/teach',
    sponsor_name: 'Federal Student Aid',
    resource_title: 'TEACH Grant',
    resource_summary: 'Official Federal Student Aid TEACH Grant page. Up to $4,000/year for students who agree to teach in a high-need field at a low-income school for four years; becomes a loan if the service obligation is not met.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education', 'scholarship', 'fafsa', 'tuition', 'professional_development'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    source_id: 'iraq_afghanistan_service_grant',
    name: 'Iraq and Afghanistan Service Grant',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov/understand-aid/types/grants/iraq-afghanistan-service',
    sponsor_name: 'Federal Student Aid',
    resource_title: 'Iraq and Afghanistan Service Grant',
    resource_summary: 'Official Federal Student Aid page. Grant for students whose parent or guardian died as a result of U.S. military service in Iraq or Afghanistan after 9/11 and who were under 24 or enrolled at the time. Does not need to be repaid.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education', 'scholarship', 'fafsa', 'tuition', 'veterans', 'survivor_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 67,
  },
  {
    source_id: 'us_dept_of_ed',
    name: 'U.S. Department of Education grant programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www2.ed.gov/fund/grant.html',
    sponsor_name: 'U.S. Department of Education',
    resource_title: 'U.S. Department of Education grants',
    resource_summary: 'Official Department of Education grant-program page for schools, districts, states, nonprofits, and education partners.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['school', 'government', 'nonprofit', 'teacher'],
    need_categories: ['education', 'curriculum', 'classroom_supplies', 'special_education', 'professional_development', 'technology'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 64,
  },
  // --- Additional official/program lanes. Most static program pages below use
  //     the generic officialDirectory adapter so they surface as honest
  //     directories or program pages, never as fabricated "apply now" grants. ---
  {
    source_id: 'usda_rd',
    name: 'USDA Rural Development programs',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.rd.usda.gov',
    directory: false, loan_allowed: true, cost_share_allowed: true,
    applicant_types: ['farm', 'government', 'business', 'vfd'],
    need_categories: ['capital', 'equipment', 'operations', 'energy'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 55,
  },
  {
    source_id: 'fema_afg',
    name: 'FEMA Assistance to Firefighters Grants',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fema.gov',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['vfd', 'government'],
    need_categories: ['equipment', 'emergency', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECT_GRANT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 65,
  },
  {
    source_id: 'usda_rd_community_facilities',
    name: 'USDA Rural Development Community Facilities',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.rd.usda.gov/programs-services/community-facilities',
    sponsor_name: 'USDA Rural Development',
    resource_title: 'USDA RD Community Facilities programs',
    resource_summary: 'Official USDA Rural Development Community Facilities program entry point for essential community facilities in rural areas.',
    directory: true, loan_allowed: true, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'school', 'vfd'],
    need_categories: ['community_facilities', 'capital', 'infrastructure', 'public_safety', 'medical', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 62,
  },
  {
    source_id: 'fema_public_assistance',
    name: 'FEMA Public Assistance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fema.gov/assistance/public',
    sponsor_name: 'Federal Emergency Management Agency',
    resource_title: 'FEMA Public Assistance',
    resource_summary: 'Official FEMA Public Assistance program information for eligible public entities and certain nonprofits after declared disasters.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'vfd', 'nonprofit'],
    need_categories: ['emergency', 'infrastructure', 'community_facilities', 'public_safety'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 61,
  },
  {
    source_id: 'fema_hazard_mitigation',
    name: 'FEMA Hazard Mitigation Assistance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fema.gov/grants/mitigation',
    sponsor_name: 'Federal Emergency Management Agency',
    resource_title: 'FEMA Hazard Mitigation Assistance',
    resource_summary: 'Official FEMA mitigation grants entry point for hazard mitigation, flood mitigation, and resilience programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'vfd', 'nonprofit'],
    need_categories: ['emergency', 'infrastructure', 'environmental_remediation', 'public_safety'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 60,
  },
  {
    source_id: 'cdbg_state_local',
    name: 'HUD Community Development Block Grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.hud.gov/program_offices/comm_planning/cdbg',
    sponsor_name: 'U.S. Department of Housing and Urban Development',
    resource_title: 'Community Development Block Grant program',
    resource_summary: 'Official HUD CDBG program page for community development, housing, public facilities, and eligible state/local pass-through activities.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit'],
    need_categories: ['housing_development', 'community_facilities', 'infrastructure', 'economic_development', 'housing'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 63,
  },
  {
    source_id: 'eda_economic_development',
    name: 'Economic Development Administration funding',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.eda.gov/funding',
    sponsor_name: 'U.S. Economic Development Administration',
    resource_title: 'EDA funding opportunities',
    resource_summary: 'Official EDA funding page for economic development, public works, infrastructure, recovery, and planning programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'business'],
    need_categories: ['economic_development', 'infrastructure', 'community_facilities', 'broadband', 'workforce'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 62,
  },
  {
    source_id: 'dot_transportation_grants',
    name: 'U.S. DOT grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.transportation.gov/grants',
    sponsor_name: 'U.S. Department of Transportation',
    resource_title: 'DOT grant programs',
    resource_summary: 'Official DOT grants entry point for transportation, safety, bridge, transit, and community mobility programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'school'],
    need_categories: ['roads_transportation', 'transportation', 'infrastructure', 'public_safety', 'school_transportation'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 62,
  },
  {
    source_id: 'epa_water_infrastructure',
    name: 'EPA grants and water infrastructure',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.epa.gov/grants',
    sponsor_name: 'U.S. Environmental Protection Agency',
    resource_title: 'EPA grants',
    resource_summary: 'Official EPA grants page for environmental, water, brownfields, and environmental-justice programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'school'],
    need_categories: ['water_sewer', 'environmental_remediation', 'infrastructure', 'medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 61,
  },
  {
    source_id: 'broadband_grants',
    name: 'BroadbandUSA funding programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://broadbandusa.ntia.doc.gov/funding-programs',
    sponsor_name: 'National Telecommunications and Information Administration',
    resource_title: 'BroadbandUSA funding programs',
    resource_summary: 'Official NTIA BroadbandUSA funding page for broadband, digital equity, and connectivity programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'school', 'business'],
    need_categories: ['broadband', 'technology', 'infrastructure', 'community_facilities', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 61,
  },
  {
    source_id: 'studentaid_gov',
    name: 'Federal Student Aid (studentaid.gov)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://studentaid.gov',
    // Truth-in-registry: the studentAidGov adapter is family:'directory' and
    // emits OPPORTUNITY_KIND.DIRECTORY with apply_url:null (there is no single
    // apply endpoint to scrape). The registry must agree so the planner counts
    // this as a directory/locator, not a direct scholarship funder.
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'family'],
    need_categories: ['education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  // (CareerOneStop Scholarship Finder was removed here on 2026-06-23: DOL
  // retired the scholarship Web API — their 21 live services include none, and
  // scholarship* endpoints 404 while occupation returns 200 with the same token.
  // If DOL reinstates it, re-add a row plus a thin adapter.)
  //
  // --- Net-new key-free federal lanes (2026-06-24) ---------------------------
  {
    source_id: 'federal_register',
    name: 'Federal Register — funding notices (NOFO/NOFA)',
    source_type: 'api',
    trust_tier: TRUST_TIER.OFFICIAL_API,
    base_url: 'https://www.federalregister.gov',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    // Federal NOFOs are institutional (agencies fund orgs/govts), so this lane
    // is gated OUT for individuals/students — the same precision as grants.gov.
    applicant_types: ['nonprofit', 'school', 'government', 'business', 'vfd', 'farm'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api', requires_env: [], refresh_frequency_days: 1, priority_score: 80,
  },
  {
    source_id: 'nih_guide',
    name: 'NIH Guide for Grants & Contracts (funding opportunities)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://grants.nih.gov/grants/guide/newsfeed/fundingopps.xml',
    feed_url: 'https://grants.nih.gov/grants/guide/newsfeed/fundingopps.xml',
    sponsor_name: 'U.S. National Institutes of Health',
    directory: false, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'school', 'government', 'business'],
    // Research/health-leaning (NOT '*'): only profiles whose needs overlap (or
    // have no specific needs) pull NIH notices, so a fire dept needing turnout
    // gear isn't shown research R01s. The match engine still scores relevance.
    need_categories: ['medical', 'programs', 'technology', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 7, priority_score: 70,
  },
  {
    source_id: 'united_way_211',
    name: '211 local assistance directory',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.211.org/get-help',
    sponsor_name: '211',
    resource_title: '211 local assistance finder',
    resource_summary: 'Connects people to local help for food, housing, utilities, health care, transportation, legal aid, and crisis needs. This is a directory, not a direct grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'student', 'veteran'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'emergency', 'legal', 'caregiving', 'survivor_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 75,
  },
  {
    source_id: 'donorschoose',
    name: 'DonorsChoose classroom funding',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.donorschoose.org/teachers',
    sponsor_name: 'DonorsChoose',
    resource_title: 'DonorsChoose teacher project funding',
    resource_summary: 'Teacher-facing classroom project funding platform for supplies, books, technology, and student materials. GrantFlow treats this as a portal/directory, not a guaranteed award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['teacher', 'school'],
    need_categories: ['education', 'equipment', 'technology'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    source_id: 'cancer_care',
    name: 'CancerCare financial assistance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.cancercare.org/financial_assistance',
    sponsor_name: 'CancerCare',
    resource_title: 'CancerCare financial assistance',
    resource_summary: 'Financial and practical-support assistance information for people affected by cancer. Eligibility and available funds vary, so this is surfaced for review rather than promised as an award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['cancer_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'ssa_survivors',
    name: 'Social Security survivors benefits',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.ssa.gov/survivor',
    sponsor_name: 'Social Security Administration',
    resource_title: 'Social Security survivors benefits',
    resource_summary: 'Official Social Security survivor-benefits information for eligible surviving spouses, children, and families. This is a benefits lane, not a grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['survivor_benefits', 'housing', 'food', 'medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'dol_black_lung_benefits',
    name: 'DOL Black Lung Program',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dol.gov/agencies/owcp/dcmwc/filing_guide_survivor',
    sponsor_name: 'U.S. Department of Labor',
    resource_title: 'Black Lung Program benefits',
    resource_summary: 'Official Department of Labor Black Lung Program information for eligible coal miners and surviving family members. GrantFlow treats this as benefit guidance, not an open grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['black_lung_benefits'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  {
    source_id: 'alzheimers_gov_services',
    name: 'Alzheimers.gov local services',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.alzheimers.gov/life-with-dementia/find-local-services',
    sponsor_name: 'Alzheimers.gov',
    resource_title: 'Dementia local services finder',
    resource_summary: 'Official federal dementia resource for finding local services, support, and care resources for people living with dementia and their caregivers.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['dementia_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  {
    source_id: 'kynect_benefits',
    name: 'Kentucky kynect benefits',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://kynect.ky.gov/benefits/s/?language=en_US',
    sponsor_name: 'Commonwealth of Kentucky',
    resource_title: 'Kentucky kynect benefits',
    resource_summary: 'Official Kentucky benefits portal for programs such as health coverage, food assistance, child care, and other household supports.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'caregiving', 'survivor_benefits'],
    geography: { national: false, states: ['KY'] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 78,
  },
  {
    source_id: 'ana_grants',
    name: 'Administration for Native Americans grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.acf.hhs.gov/ana/grants',
    sponsor_name: 'Administration for Native Americans',
    resource_title: 'Administration for Native Americans grants',
    resource_summary: 'Official Administration for Native Americans grants resource for tribal governments, Native nonprofits, and Native communities.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['tribal', 'government', 'nonprofit'],
    need_categories: ['capital', 'operations', 'programs', 'technology', 'public_safety', 'agriculture', 'recreation', 'energy'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'bia_tribal_programs',
    name: 'Bureau of Indian Affairs grants and services',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.bia.gov/service/grants',
    sponsor_name: 'Bureau of Indian Affairs',
    resource_title: 'BIA grants and services',
    resource_summary: 'Official BIA grants and services entry point for tribal governments, tribal organizations, and Native communities.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['tribal', 'government'],
    need_categories: ['housing_development', 'community_facilities', 'medical', 'public_safety', 'education', 'broadband', 'infrastructure', 'economic_development'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'imls_library_museum',
    name: 'Institute of Museum and Library Services grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.imls.gov/grants',
    sponsor_name: 'Institute of Museum and Library Services',
    resource_title: 'IMLS grants',
    resource_summary: 'Official IMLS grant page for libraries, museums, archives, and related public or nonprofit institutions.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'government', 'school'],
    need_categories: ['library_media', 'community_facilities', 'education', 'technology', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 64,
  },
  {
    source_id: 'cdc_grants',
    name: 'CDC grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.cdc.gov/grants',
    sponsor_name: 'Centers for Disease Control and Prevention',
    resource_title: 'CDC grants',
    resource_summary: 'Official CDC grants page for public-health departments, tribes, nonprofits, schools, and eligible partners.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'school'],
    need_categories: ['medical', 'mental_health', 'substance_recovery', 'public_safety', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 66,
  },
  {
    source_id: 'samhsa_grants',
    name: 'SAMHSA grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.samhsa.gov/grants',
    sponsor_name: 'Substance Abuse and Mental Health Services Administration',
    resource_title: 'SAMHSA grants',
    resource_summary: 'Official SAMHSA grants page for mental health, substance-use recovery, prevention, and behavioral-health programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'school'],
    need_categories: ['mental_health', 'substance_recovery', 'medical', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 67,
  },
  {
    source_id: 'hud_homeless_assistance',
    name: 'HUD homeless assistance programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.hud.gov/program_offices/comm_planning/homeless',
    sponsor_name: 'U.S. Department of Housing and Urban Development',
    resource_title: 'HUD homeless assistance',
    resource_summary: 'Official HUD homeless-assistance entry point for Continuum of Care, Emergency Solutions Grants, and related homelessness programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'church', 'ministry'],
    need_categories: ['housing', 'housing_development', 'mental_health', 'medical', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 66,
  },
  {
    source_id: 'ovw_grants',
    name: 'Office on Violence Against Women grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.justice.gov/ovw/grant-programs',
    sponsor_name: 'U.S. Department of Justice Office on Violence Against Women',
    resource_title: 'OVW grant programs',
    resource_summary: 'Official DOJ OVW grant-program page for violence-prevention, survivor services, transitional housing, and related justice programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'law_enforcement'],
    need_categories: ['domestic_violence', 'housing', 'mental_health', 'public_safety', 'legal', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 66,
  },
  {
    source_id: 'bja_second_chance',
    name: 'BJA Second Chance Act resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://bja.ojp.gov/program/second-chance-act/overview',
    sponsor_name: 'Bureau of Justice Assistance',
    resource_title: 'Second Chance Act program',
    resource_summary: 'Official BJA Second Chance Act overview for reentry, reintegration, and justice-involved workforce/community programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'church', 'ministry'],
    need_categories: ['reentry', 'workforce', 'employment', 'housing', 'mental_health', 'substance_recovery', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 65,
  },
  {
    source_id: 'petsmart_charities_grants',
    name: 'PetSmart Charities grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.VERIFIED_FOUNDATION,
    base_url: 'https://petsmartcharities.org/pro/grants',
    sponsor_name: 'PetSmart Charities',
    resource_title: 'PetSmart Charities grant programs',
    resource_summary: 'Animal-welfare grant program page for eligible animal shelters, rescues, and community partners. GrantFlow treats this as a portal/directory until a specific open grant is parsed.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['nonprofit', 'government'],
    need_categories: ['animal_welfare', 'capacity_building', 'equipment', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 63,
  },
  {
    source_id: 'petco_love_grants',
    name: 'Petco Love grant opportunities',
    source_type: 'directory',
    trust_tier: TRUST_TIER.VERIFIED_FOUNDATION,
    base_url: 'https://petcolove.org/partners/grants/',
    sponsor_name: 'Petco Love',
    resource_title: 'Petco Love grant opportunities',
    resource_summary: 'Animal-welfare grant portal for eligible shelter and rescue partners. GrantFlow treats this as a portal/directory until a specific open grant is parsed.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['nonprofit', 'government'],
    need_categories: ['animal_welfare', 'capacity_building', 'equipment', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 62,
  },
  {
    source_id: 'aspca_grants',
    name: 'ASPCA grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.VERIFIED_FOUNDATION,
    base_url: 'https://www.aspcapro.org/grants',
    sponsor_name: 'ASPCA',
    resource_title: 'ASPCA grants',
    resource_summary: 'Animal-welfare grant information for eligible organizations. GrantFlow treats this as a portal/directory until a specific open grant is parsed.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['nonprofit', 'government'],
    need_categories: ['animal_welfare', 'capacity_building', 'equipment', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 61,
  },
  {
    source_id: 'sba_grants',
    name: 'SBA grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/funding-programs/grants',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'SBA grants',
    resource_summary: 'Official SBA grants page. SBA grants are limited and are not ordinary practice-startup money; loans are not surfaced here unless a profile explicitly allows loan products elsewhere.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['business', 'farm'],
    need_categories: ['capital', 'operations', 'technology', 'agriculture', 'legal', 'startup', 'equipment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 62,
  },
  {
    source_id: 'sba_veteran_business',
    name: 'SBA veteran-owned business resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/business-guide/grow-your-business/veteran-owned-businesses',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'SBA veteran-owned business resources',
    resource_summary: 'Official SBA resource page for veterans, service members, and military spouses starting or growing a business. This is resource guidance, not guaranteed funding.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['veteran', 'active_duty', 'guard_reserve', 'transitioning_service_member', 'military_spouse'],
    need_categories: ['veteran_startup', 'military_startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'sba_vboc',
    name: 'SBA Veterans Business Outreach Centers',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/local-assistance/resource-partners/veterans-business-outreach-centers-vboc',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'Veterans Business Outreach Center program',
    resource_summary: 'Official SBA VBOC program resource for veteran and military-community entrepreneurs seeking business training, counseling, and startup support.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['veteran', 'active_duty', 'guard_reserve', 'transitioning_service_member', 'military_spouse'],
    need_categories: ['veteran_startup', 'military_startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 71,
  },
  {
    source_id: 'military_onesource',
    name: 'Military OneSource',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.militaryonesource.mil/',
    sponsor_name: 'U.S. Department of Defense',
    resource_title: 'Military OneSource support resources',
    resource_summary: 'Official Department of Defense support portal for service members, military spouses, and families. Covers active-duty, Guard/Reserve, transition, education, career, financial, and family support resources.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['active_duty', 'guard_reserve', 'transitioning_service_member', 'military_spouse'],
    need_categories: ['active_duty_support', 'military_transition', 'military_spouse_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 73,
  },
  {
    source_id: 'mycaa',
    name: 'MyCAA Scholarship',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://mycaa.militaryonesource.mil/mycaa/',
    sponsor_name: 'U.S. Department of Defense',
    resource_title: 'MyCAA Scholarship',
    resource_summary: 'Official Military Spouse Career Advancement Account Scholarship portal for eligible military spouses pursuing licenses, certificates, certifications, or associate degrees.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['military_spouse'],
    need_categories: ['military_spouse_support', 'education', 'employment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'dol_tap',
    name: 'DOL Transition Assistance Program',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dol.gov/agencies/vets/programs/tap',
    sponsor_name: 'U.S. Department of Labor',
    resource_title: 'Transition Assistance Program employment resources',
    resource_summary: 'Official DOL VETS transition employment resource for separating and transitioning service members, veterans, and military spouses.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['transitioning_service_member', 'active_duty', 'veteran', 'military_spouse'],
    need_categories: ['military_transition', 'employment', 'startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'sba_boots_to_business',
    name: 'SBA Boots to Business',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.sba.gov/sba-learning-platform/boots-business',
    sponsor_name: 'U.S. Small Business Administration',
    resource_title: 'Boots to Business entrepreneurship training',
    resource_summary: 'Official SBA entrepreneurship training resource for transitioning service members, veterans, National Guard/Reserve members, and military spouses.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['transitioning_service_member', 'active_duty', 'guard_reserve', 'veteran', 'military_spouse'],
    need_categories: ['military_startup', 'veteran_startup'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'wv_sbdc_funding',
    name: 'West Virginia SBDC funding resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://wvsbdc.com/services/funding/',
    sponsor_name: 'West Virginia Small Business Development Center',
    resource_title: 'WV SBDC funding resources',
    resource_summary: 'West Virginia Small Business Development Center funding-resource page for small business owners and startup founders. Loan products still remain gated by user preference.',
    directory: true, loan_allowed: true, cost_share_allowed: false,
    applicant_types: ['business', 'individual', 'veteran'],
    need_categories: ['startup', 'capital', 'operations', 'equipment'],
    geography: { national: false, states: ['WV'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 73,
  },
  {
    source_id: 'wv_business_funding_resources',
    name: 'West Virginia business funding resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://sos.wv.gov/business/general-information/funding-grant-resources',
    sponsor_name: 'West Virginia Secretary of State',
    resource_title: 'West Virginia funding and grant resources',
    resource_summary: 'Official West Virginia business funding-resource page listing organizations that offer funding, loans, grants, and guidance for West Virginia businesses. Loan products remain gated by user preference.',
    directory: true, loan_allowed: true, cost_share_allowed: false,
    applicant_types: ['business', 'individual', 'veteran'],
    need_categories: ['startup', 'capital', 'operations', 'equipment'],
    geography: { national: false, states: ['WV'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'lsc_grants',
    name: 'Legal Services Corporation grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.lsc.gov/grants',
    sponsor_name: 'Legal Services Corporation',
    resource_title: 'Legal Services Corporation grants',
    resource_summary: 'Official LSC grant information for civil legal aid organizations. This is for eligible legal-services organizations, not a general private law-practice grant.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'government'],
    need_categories: ['legal', 'programs', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 58,
  },
  {
    source_id: 'oregon_parks_rec_grants',
    name: 'Oregon Parks and Recreation Department grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.oregon.gov/oprd/GRA/Pages/GRA-overview.aspx',
    sponsor_name: 'Oregon Parks and Recreation Department',
    resource_title: 'Oregon parks and recreation grant programs',
    resource_summary: 'Official Oregon parks and recreation grants overview for public recreation, trails, parks, heritage, and local government projects.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'nonprofit'],
    need_categories: ['recreation', 'capital', 'equipment', 'programs'],
    geography: { national: false, states: ['OR'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  {
    source_id: 'dhs_grants',
    name: 'DHS grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dhs.gov/dhs-grants',
    sponsor_name: 'U.S. Department of Homeland Security',
    resource_title: 'DHS grants',
    resource_summary: 'Official DHS grants page for preparedness, security, emergency management, and homeland-security programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'vfd', 'law_enforcement'],
    need_categories: ['public_safety', 'emergency', 'equipment', 'technology', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 73,
  },
  {
    source_id: 'doj_grants',
    name: 'Department of Justice grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.justice.gov/grants',
    sponsor_name: 'U.S. Department of Justice',
    resource_title: 'Department of Justice grants',
    resource_summary: 'Official DOJ grants page for public safety, legal services, violence prevention, victim services, and justice programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'law_enforcement'],
    need_categories: ['public_safety', 'legal', 'programs', 'technology'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 71,
  },
  {
    source_id: 'cops_grants',
    name: 'COPS Office grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://cops.usdoj.gov/grants',
    sponsor_name: 'U.S. Department of Justice COPS Office',
    resource_title: 'COPS Office grants',
    resource_summary: 'Official COPS Office grants page for community policing, law-enforcement hiring, equipment, training, and public-safety programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'law_enforcement'],
    need_categories: ['public_safety', 'equipment', 'technology', 'programs'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 70,
  },
  {
    source_id: 'fec_candidate_resources',
    name: 'FEC candidate and committee resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.fec.gov/help-candidates-and-committees/',
    sponsor_name: 'Federal Election Commission',
    resource_title: 'FEC candidate and committee resources',
    resource_summary: 'Official federal campaign-finance resource. This is compliance/funding-process guidance, not a grant or award.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['candidate'],
    need_categories: ['campaign', 'operations'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 64,
  },
  {
    source_id: 'pa_campaign_finance',
    name: 'Pennsylvania campaign finance',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.pa.gov/agencies/dos/programs/voting-and-elections/campaign-finance',
    sponsor_name: 'Pennsylvania Department of State',
    resource_title: 'Pennsylvania campaign finance resources',
    resource_summary: 'Official Pennsylvania campaign-finance resource for candidates and committees. This is state compliance/funding-process guidance, not a grant or guaranteed funding source.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['candidate'],
    need_categories: ['campaign', 'operations'],
    geography: { national: false, states: ['PA'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  // --- Orphaned funding lanes ported into the OS (2026-07-07, owner directive:
  //     "if there are other crawler lanes that got left out like ECF, port them
  //     in too"). propublica_990 is a REAL API lane (IRS 990 grantmakers); the
  //     rest are honest official program/directory rows via the generic
  //     officialDirectory adapter — never fabricated "apply now" grants. -------
  {
    // IRS 990 grantmaker discovery. ProPublica's Nonprofit Explorer indexes
    // 1.8M+ nonprofit 990 filings (free public API, no key) — the dataset
    // GrantWatch/Candid charge for. The adapter searches grantmaking
    // foundations (NTEE-driven, state-scoped from the profile thesis) and
    // surfaces each as an approach-the-funder PROGRAM row with the ProPublica
    // profile as info_url; it NEVER invents an apply URL or a deadline.
    source_id: 'propublica_990',
    name: 'ProPublica Nonprofit Explorer (IRS 990 grantmakers)',
    source_type: 'api',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://projects.propublica.org/nonprofits/api',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['nonprofit', 'school', 'church', 'ministry', 'government'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.PROGRAM],
    crawler_method: 'api', requires_env: [], refresh_frequency_days: 7, priority_score: 78,
  },
  {
    source_id: 'arc_dra',
    name: 'Appalachian Regional Commission grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.arc.gov/grants/',
    sponsor_name: 'Appalachian Regional Commission',
    resource_title: 'Appalachian Regional Commission grant programs',
    resource_summary: 'Official ARC grants entry point for economic development, infrastructure, workforce, broadband, and health projects in the 13 Appalachian states.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'tribal', 'nonprofit', 'business'],
    need_categories: ['economic_development', 'infrastructure', 'workforce', 'broadband', 'medical'],
    geography: { national: false, states: ['WV', 'KY', 'OH', 'PA', 'TN', 'VA', 'NC', 'GA', 'AL', 'MS', 'SC', 'MD', 'NY'] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 68,
  },
  {
    // NOTE: 'refugee' is not an OS need slug — ORR's cash/medical assistance,
    // employment, and resettlement services map to the existing taxonomy needs
    // below (housing/employment/education/medical/legal).
    source_id: 'orr_refugee',
    name: 'HHS Office of Refugee Resettlement programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.acf.hhs.gov/orr',
    sponsor_name: 'HHS Office of Refugee Resettlement',
    resource_title: 'Office of Refugee Resettlement programs',
    resource_summary: 'Official ORR entry point for refugee cash and medical assistance, employment services, and resettlement support programs, for refugees/new arrivals and the organizations serving them.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['nonprofit', 'government', 'individual', 'family'],
    need_categories: ['housing', 'employment', 'education', 'medical', 'legal'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  {
    // NOTE: 'foster_youth' is not an OS need slug — Chafee serves current/former
    // foster youth with education, housing, and employment support, which map to
    // the existing taxonomy needs below.
    source_id: 'acf_chafee_foster',
    name: 'Chafee program for youth aging out of foster care',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.acf.hhs.gov/cb/program-guide/chafee',
    sponsor_name: 'HHS Administration for Children and Families',
    resource_title: 'John H. Chafee Foster Care Program for Successful Transition to Adulthood',
    resource_summary: 'Official Chafee program information for current and former foster youth: education and training vouchers, housing, employment, and transition-to-adulthood support. This is a benefits lane administered by states.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'student'],
    need_categories: ['education', 'housing', 'employment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    source_id: 'ccdf_childcare',
    name: 'Childcare.gov (Child Care and Development Fund assistance)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://childcare.gov',
    sponsor_name: 'HHS Office of Child Care',
    resource_title: 'Childcare.gov child care assistance',
    resource_summary: 'Official federal child-care portal for finding state CCDF child-care subsidies and other help paying for child care for working and studying families.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['childcare', 'education', 'employment'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 68,
  },
  {
    // NOTE: 'displaced_worker' is not an OS need slug — dislocated-worker
    // programs are covered by the existing 'workforce'/'employment' needs.
    source_id: 'dol_eta_workforce',
    name: 'DOL Employment and Training Administration grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.dol.gov/agencies/eta/grants',
    sponsor_name: 'U.S. Department of Labor Employment and Training Administration',
    resource_title: 'DOL ETA workforce grants',
    resource_summary: 'Official DOL ETA grants page for workforce development, job training, apprenticeship, and dislocated-worker programs.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['government', 'nonprofit', 'individual'],
    need_categories: ['workforce', 'employment', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 66,
  },
  {
    // NOTE: 'arts' is not an OS need slug — mapped to the existing
    // 'arts_education' need (nearest taxonomy category).
    source_id: 'nea_neh_arts',
    name: 'National Endowment for the Arts grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.arts.gov/grants',
    sponsor_name: 'National Endowment for the Arts',
    resource_title: 'NEA grants',
    resource_summary: 'Official National Endowment for the Arts grants page for arts organizations, communities, schools, and individual artists/writers (fellowships).',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['nonprofit', 'government', 'school', 'individual'],
    need_categories: ['arts_education', 'programs', 'education'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 63,
  },
  {
    source_id: 'usda_conservation',
    name: 'USDA NRCS conservation programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.nrcs.usda.gov/programs',
    sponsor_name: 'USDA Natural Resources Conservation Service',
    resource_title: 'NRCS conservation programs (EQIP, CSP, and more)',
    resource_summary: 'Official USDA NRCS programs page for conservation cost-share and easement programs for farmers, ranchers, tribes, and local governments: soil, water, energy, and environmental improvements.',
    directory: true, loan_allowed: false, cost_share_allowed: true,
    applicant_types: ['farm', 'government', 'tribal'],
    need_categories: ['agriculture', 'environmental_remediation', 'water_sewer', 'energy'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 66,
  },
  {
    source_id: 'hrsa_health_workforce',
    name: 'HRSA Bureau of Health Workforce programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://bhw.hrsa.gov',
    sponsor_name: 'HRSA Bureau of Health Workforce',
    resource_title: 'HRSA health workforce programs (scholarships, loan repayment, grants)',
    resource_summary: 'Official HRSA Bureau of Health Workforce entry point: NHSC/NURSE Corps scholarships and loan repayment for health-profession students and clinicians, plus workforce grants for training organizations.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'nonprofit', 'government'],
    need_categories: ['education', 'medical', 'employment', 'professional_development'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 14, priority_score: 65,
  },
  {
    source_id: 'copay_assistance_foundations',
    name: 'NeedyMeds copay and medical assistance programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.needymeds.org',
    sponsor_name: 'NeedyMeds',
    resource_title: 'NeedyMeds medication and healthcare cost assistance finder',
    resource_summary: 'Directory of patient-assistance programs, copay assistance foundations, drug discount programs, and diagnosis-based medical financial aid. A directory/referral lane, not a direct cash grant.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['medical', 'medication', 'medical_bills', 'cancer_support'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
  {
    // SAH/SHA are REAL grants (statutory dollar caps, real application via
    // VA Form 26-4555), so this is a DIRECT_GRANT lane, not a directory.
    source_id: 'va_housing_grants',
    name: 'VA disability housing grants (SAH/SHA)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.va.gov/housing-assistance/disability-housing-grants/',
    sponsor_name: 'U.S. Department of Veterans Affairs',
    resource_title: 'VA Specially Adapted Housing (SAH) and Special Home Adaptation (SHA) grants',
    resource_summary: 'Official VA disability housing grants for veterans and service members with qualifying service-connected disabilities: buy, build, or adapt a home for independent living. Apply online or with VA Form 26-4555.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['veteran', 'active_duty'],
    need_categories: ['housing', 'disability', 'veterans'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECT_GRANT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  // ── County & city programs lane (2026-07-08) — the fleet's #1 structural
  //    gap: EVERY scanned profile lacked a county_city source. These are honest
  //    national LOCATORS that resolve to the profile's own county/city via the
  //    geo-aware countyCityDirectoryAdapter (candidate is titled with the
  //    profile's place and, where the site supports it, deep-linked by ZIP). ──
  {
    source_id: 'usa_gov_local_governments',
    name: 'USA.gov local government directory',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.usa.gov/local-governments',
    sponsor_name: 'USA.gov',
    resource_title: 'County & city government assistance programs (USA.gov directory)',
    resource_summary: 'Official USA.gov index of city, county, and town government websites — the front door to locally administered assistance (housing, utility, emergency, human services) that never appears in federal or state catalogs.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['*'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 62,
  },
  {
    source_id: 'hud_resource_locator',
    name: 'HUD Resource Locator (local housing offices & programs)',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://resources.hud.gov',
    sponsor_name: 'U.S. Department of Housing and Urban Development',
    resource_title: 'Local housing help — HUD Resource Locator',
    resource_summary: 'Official HUD map/locator for local Public Housing Agencies, HUD-approved housing counselors, multifamily and homeless-assistance resources near a given address — county/city-level housing help.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    // NOTE: homelessness maps to the OS 'housing' need slug (no separate slug).
    need_categories: ['housing', 'emergency'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 64,
  },
  {
    source_id: 'findhelp_local_programs',
    name: 'findhelp.org local assistance programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.findhelp.org',
    // ZIP-scoped deep link — the countyCityDirectoryAdapter substitutes the
    // profile's ZIP so the candidate lands on THEIR county/city programs.
    url_template: 'https://www.findhelp.org/search_results/{zip}',
    sponsor_name: 'findhelp (Aunt Bertha)',
    resource_title: 'Local assistance programs near you (findhelp)',
    resource_summary: 'ZIP-code-driven directory of free and reduced-cost local programs (food, housing, transit, money, care) run by county agencies, cities, churches, and charities — the hyperlocal safety-net layer.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['*'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 66,
  },
  // ── State-programs lane: OH + WA (adapter-wishlist states 2026-07-08;
  //    2 OH profiles + 1 WA profile had NO state-specific source). Mirrors the
  //    kynect_benefits (KY) shape: official portal, honest BENEFIT locator. ──
  {
    source_id: 'oh_benefits',
    name: 'Ohio Benefits portal',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://benefits.ohio.gov',
    sponsor_name: 'State of Ohio',
    resource_title: 'Ohio Benefits (state assistance portal)',
    resource_summary: 'Official Ohio benefits portal for Medicaid health coverage, SNAP food assistance, cash assistance (Ohio Works First), child care, and other household supports.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'caregiving', 'childcare', 'survivor_benefits'],
    geography: { national: false, states: ['OH'] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 78,
  },
  {
    source_id: 'oh_college_opportunity_grant',
    name: 'Ohio College Opportunity Grant (OCOG)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://highered.ohio.gov/initiatives/affordability/ocog/ocog',
    sponsor_name: 'Ohio Department of Higher Education',
    resource_title: 'Ohio College Opportunity Grant (OCOG)',
    resource_summary: 'Ohio\'s need-based state grant for resident undergraduates (FAFSA-driven, awarded by EFC/SAI and income) at Ohio public, private, and eligible proprietary institutions.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'individual'],
    need_categories: ['education'],
    geography: { national: false, states: ['OH'] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  {
    source_id: 'wa_connection_benefits',
    name: 'Washington Connection benefits portal',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://www.washingtonconnection.org',
    sponsor_name: 'Washington State DSHS',
    resource_title: 'Washington Connection (state assistance portal)',
    resource_summary: 'Official Washington State portal (DSHS) for food, cash, child care, long-term care, and Medicare Savings programs — one application across WA household supports.',
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran', 'student'],
    need_categories: ['housing', 'food', 'medical', 'energy', 'caregiving', 'childcare', 'survivor_benefits'],
    geography: { national: false, states: ['WA'] },
    default_kinds: [OPPORTUNITY_KIND.BENEFIT],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 78,
  },
  {
    source_id: 'wa_college_grant',
    name: 'Washington College Grant (WSAC)',
    source_type: 'html',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://wsac.wa.gov/wcg',
    sponsor_name: 'Washington Student Achievement Council',
    resource_title: 'Washington College Grant',
    resource_summary: 'Washington\'s largest state financial-aid program: income-based grants covering up to full tuition at WA public colleges, universities, and approved career-training programs.',
    directory: false, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['student', 'individual'],
    need_categories: ['education'],
    geography: { national: false, states: ['WA'] },
    default_kinds: [OPPORTUNITY_KIND.SCHOLARSHIP],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 76,
  },
  // ── Disease-specific lane: mobility impairment + neurodivergent (adapter
  //    wishlist 2026-07-08 — 2 profiles each had NO disease-specific source).
  //    `keywords` feed coverageEvidenceService.conditionCoveredBySource. ──
  {
    source_id: 'reeve_foundation_paralysis',
    name: 'Christopher & Dana Reeve Foundation — paralysis & mobility support',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.christopherreeve.org/todays-care/get-support/',
    sponsor_name: 'Christopher & Dana Reeve Foundation',
    resource_title: 'Reeve Foundation paralysis & mobility-impairment support',
    resource_summary: 'National Paralysis Resource Center: information specialists, peer support, and pointers to financial help (adaptive equipment, home modification, wheelchair funding) for people living with paralysis or mobility impairment.',
    keywords: ['mobility impairment', 'mobility', 'paralysis', 'spinal cord injury', 'wheelchair', 'adaptive equipment'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['medical', 'disability'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'autism_speaks_family_support',
    name: 'Autism Speaks family services & financial resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.autismspeaks.org/financial-autism-support',
    sponsor_name: 'Autism Speaks',
    resource_title: 'Autism & neurodivergent family financial-support resources',
    resource_summary: 'Directory of financial supports for autistic and neurodivergent people and their families: family grant programs, care funding, ABLE accounts, and state/community resources.',
    keywords: ['neurodivergent', 'autism', 'adhd', 'developmental disability', 'neurodiversity'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family'],
    need_categories: ['medical', 'disability', 'caregiving'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  // ── Disease-specific lane: adapter wishlist 2026-07-11 (Amy: hip
  //    replacement ×2, PTSD, chronic kidney disease, hypertension profiles
  //    each had NO disease-specific source). Same honest-locator shape. ──
  {
    source_id: 'arthritis_foundation_help',
    name: 'Arthritis Foundation — joint surgery & mobility resources',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.arthritis.org/liveyes/helpline',
    sponsor_name: 'Arthritis Foundation',
    resource_title: 'Arthritis Foundation help line & financial-resource navigation',
    resource_summary: 'National helpline and resource navigation for people with arthritis or facing joint-replacement surgery: financial-assistance pointers (treatment costs, insurance appeals, medication programs), care planning, and local support.',
    keywords: ['hip replacement', 'joint replacement', 'knee replacement', 'arthritis', 'orthopedic surgery', 'joint surgery'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['medical', 'disability'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 72,
  },
  {
    source_id: 'samhsa_findtreatment',
    name: 'SAMHSA FindTreatment.gov — mental health & PTSD treatment locator',
    source_type: 'directory',
    trust_tier: TRUST_TIER.OFFICIAL_HTML,
    base_url: 'https://findtreatment.gov',
    sponsor_name: 'Substance Abuse and Mental Health Services Administration',
    resource_title: 'FindTreatment.gov — confidential mental-health & substance-use treatment locator',
    resource_summary: 'Official SAMHSA locator for state-licensed mental-health and substance-use treatment, including PTSD and trauma care; filters for sliding-scale fees, payment assistance, and free/low-cost programs.',
    keywords: ['ptsd', 'trauma', 'mental health treatment', 'depression', 'anxiety', 'substance use', 'counseling'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'american_kidney_fund',
    name: 'American Kidney Fund — patient assistance grants',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.kidneyfund.org/all-about-kidneys/getting-financial-help',
    sponsor_name: 'American Kidney Fund',
    resource_title: 'American Kidney Fund financial assistance (dialysis & kidney disease)',
    resource_summary: 'National patient-assistance programs for people with chronic kidney disease and kidney failure: health-insurance premium help (HIPP), emergency grants for transportation/medication/utilities, and disaster relief for dialysis patients.',
    keywords: ['chronic kidney disease', 'kidney disease', 'kidney failure', 'dialysis', 'esrd', 'renal', 'transplant'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['medical', 'disability'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 74,
  },
  {
    source_id: 'needymeds_diagnosis_assistance',
    name: 'NeedyMeds — diagnosis-based assistance programs',
    source_type: 'directory',
    trust_tier: TRUST_TIER.AGGREGATOR,
    base_url: 'https://www.needymeds.org/diagnosis_based_assistance',
    sponsor_name: 'NeedyMeds',
    resource_title: 'NeedyMeds diagnosis-based assistance directory (hypertension, heart disease & chronic conditions)',
    resource_summary: 'Directory of assistance programs organized by diagnosis — medication cost help, copay cards, and condition-specific funds for hypertension, high blood pressure, heart disease, diabetes, and other chronic conditions.',
    keywords: ['hypertension', 'high blood pressure', 'heart disease', 'diabetes', 'medication assistance', 'copay assistance', 'chronic condition'],
    directory: true, loan_allowed: false, cost_share_allowed: false,
    applicant_types: ['individual', 'family', 'veteran'],
    need_categories: ['medical'],
    geography: { national: true, states: [] },
    default_kinds: [OPPORTUNITY_KIND.DIRECTORY],
    crawler_method: 'html', requires_env: [], refresh_frequency_days: 30, priority_score: 70,
  },
]);

const BY_ID = Object.freeze(Object.fromEntries(SOURCES.map((s) => [s.source_id, s])));

export function allSources() { return SOURCES.map((s) => mergeSourceCoverage({ ...s })); }
export function getSource(id) { const s = BY_ID[id]; return s ? mergeSourceCoverage({ ...s }) : null; }
export function sourceIds() { return SOURCES.map((s) => s.source_id); }

export default { SOURCES, allSources, getSource, sourceIds };
