import React, { useState, useCallback, useRef } from 'react';
import { apiFetch } from '@/api/client';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
} from '@/components/ui/sheet';
import {
  Loader2, Printer, FileText, AlertTriangle,
  CheckCircle2, Mail, Phone, Copy, Download,
} from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { copyTextToClipboard } from '@/utils/clipboard';

function CopyButton({ text }) {
  const [copyState, setCopyState] = useState('idle');
  const copy = useCallback(async () => {
    const copied = await copyTextToClipboard(text || '');
    setCopyState(copied ? 'copied' : 'failed');
    setTimeout(() => setCopyState('idle'), 2000);
  }, [text]);
  return (
    <Button variant="ghost" size="sm" onClick={copy} className="gap-1 text-xs">
      <Copy className="w-3 h-3" />
      {copyState === 'copied' ? 'Copied' : copyState === 'failed' ? 'Copy failed' : 'Copy'}
    </Button>
  );
}

function SectionBlock({ title, children, text }) {
  return (
    <div className="mb-6 print-section">
      <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-2 border-b pb-1 flex items-center justify-between">
        {title}
        {text && <CopyButton text={text} />}
      </h3>
      <div className="text-sm text-slate-800 leading-relaxed whitespace-pre-wrap">
        {children}
      </div>
    </div>
  );
}

export default function PrintableApplicationPanel({ open, onClose, grant }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const printRef = useRef(null);
  const { toast } = useToast();

  const generateApplication = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiFetch('/api/ai/generate-printable-application', {
        method: 'POST',
        body: JSON.stringify({ grant_id: grant.id }),
      });
      if (data.success && data.application) {
        setResult(data);
      } else {
        setError(data.error || 'Failed to generate application');
      }
    } catch (err) {
      setError(err.message || 'Network error');
    } finally {
      setLoading(false);
    }
  }, [grant?.id]);

  const handlePrint = useCallback(() => {
    const el = printRef.current;
    if (!el) return;
    const win = window.open('', '_blank');
    if (!win) { toast({ title: 'Pop-up blocked', description: 'Allow pop-ups to print the application.', variant: 'destructive' }); return; }
    win.document.write(`<!DOCTYPE html><html><head><title>${result?.grant_title || 'Application'} - Print</title>
      <style>
        @page { margin: 0.75in; size: letter portrait; }
        body { font-family: 'Times New Roman', Georgia, serif; font-size: 12pt; line-height: 1.6; color: #000; max-width: 7in; margin: 0 auto; }
        h1 { font-size: 16pt; margin-bottom: 4pt; }
        h2 { font-size: 14pt; margin-top: 18pt; margin-bottom: 6pt; border-bottom: 1px solid #333; padding-bottom: 3pt; }
        h3 { font-size: 12pt; margin-top: 14pt; margin-bottom: 4pt; }
        .letterhead { text-align: right; margin-bottom: 24pt; font-size: 11pt; }
        .addressed { margin-bottom: 18pt; }
        .cover-letter { margin-bottom: 24pt; }
        .narrative { margin-bottom: 24pt; }
        .section-block { margin-bottom: 18pt; page-break-inside: avoid; }
        .signature-line { margin-top: 36pt; border-top: 1px solid #000; width: 250px; padding-top: 4pt; }
        .checklist-item { margin: 4pt 0; }
        .checklist-item::before { content: "\\2610  "; }
        .missing-badge { background: #FEF3C7; padding: 2px 8px; border-radius: 4px; font-size: 10pt; }
        .stamp { text-align: center; margin-top: 24pt; font-size: 10pt; color: #666; }
        .submission-box { border: 2px solid #000; padding: 12pt; margin: 18pt 0; }
      </style>
    </head><body>${el.innerHTML}
      <div class="stamp">Generated by GrantFlow Application Assistant</div>
    </body></html>`);
    win.document.close();
    setTimeout(() => { win.print(); }, 400);
  }, [result, toast]);

  const app = result?.application;

  return (
    <Sheet open={open} onOpenChange={(v) => !v && onClose()}>
      <SheetContent side="right" className="w-full sm:max-w-2xl overflow-hidden flex flex-col">
        <SheetHeader className="shrink-0">
          <SheetTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            Printable Application Generator
          </SheetTitle>
          <SheetDescription>
            Generate a complete, print-ready application for physical submission (mail, fax, or hand-deliver).
          </SheetDescription>
        </SheetHeader>

        <ScrollArea className="flex-1 pr-4 mt-4">
          {!result && !loading && (
            <div className="space-y-4">
              <Card className="bg-blue-50 border-blue-200">
                <CardContent className="p-4 space-y-3">
                  <h4 className="font-semibold text-blue-900">This will generate:</h4>
                  <ul className="text-sm text-blue-800 space-y-1.5 list-disc list-inside">
                    <li>Professional cover letter addressed to the funder</li>
                    <li>Statement of need / project narrative</li>
                    <li>Budget justification (if applicable)</li>
                    <li>Completed application form sections</li>
                    <li>Submission checklist with mailing/fax instructions</li>
                    <li>List of supporting documents you need to gather</li>
                  </ul>

                  {(grant?.funder_address || grant?.funder_fax) && (
                    <div className="mt-3 p-3 bg-white rounded-lg border border-blue-200">
                      <p className="text-xs font-semibold text-blue-700 uppercase mb-1">Submission Info on File</p>
                      {grant.funder_address && (
                        <p className="text-sm flex items-start gap-2"><Mail className="w-4 h-4 mt-0.5 text-slate-500" />{grant.funder_address}</p>
                      )}
                      {grant.funder_fax && (
                        <p className="text-sm flex items-start gap-2"><Phone className="w-4 h-4 mt-0.5 text-slate-500" />Fax: {grant.funder_fax}</p>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>

              <Button onClick={generateApplication} className="w-full gap-2 bg-blue-600 hover:bg-blue-700" size="lg">
                <FileText className="w-5 h-5" />
                Generate Application Package
              </Button>
            </div>
          )}

          {loading && (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <Loader2 className="w-10 h-10 animate-spin text-blue-600" />
              <p className="text-sm text-slate-600 font-medium">Writing your application at an MBA level...</p>
              <p className="text-xs text-slate-400">This takes 15–30 seconds</p>
            </div>
          )}

          {error && (
            <Card className="border-red-200 bg-red-50">
              <CardContent className="p-4 flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600 mt-0.5" />
                <div>
                  <p className="font-medium text-red-900">Generation Failed</p>
                  <p className="text-sm text-red-700 mt-1">{error}</p>
                  <Button onClick={generateApplication} variant="outline" size="sm" className="mt-3">
                    Try Again
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {app && (
            <div className="space-y-4">
              {/* Action bar */}
              <div className="flex gap-2 no-print sticky top-0 z-10 bg-white pb-2 border-b">
                <Button onClick={handlePrint} className="flex-1 gap-2 bg-green-600 hover:bg-green-700">
                  <Printer className="w-4 h-4" /> Print Application
                </Button>
                <Button onClick={generateApplication} variant="outline" className="gap-2">
                  <FileText className="w-4 h-4" /> Regenerate
                </Button>
              </div>

              {/* Submission destination box */}
              {(app.addressed_to || result?.submission) && (
                <Card className="border-2 border-slate-800 bg-amber-50">
                  <CardContent className="p-4">
                    <p className="text-xs font-bold uppercase text-slate-700 mb-2">Submit To</p>
                    {app.addressed_to?.organization && <p className="font-semibold">{app.addressed_to.organization}</p>}
                    {app.addressed_to?.name && <p className="text-sm">{app.addressed_to.name}{app.addressed_to.title ? `, ${app.addressed_to.title}` : ''}</p>}
                    {(app.addressed_to?.address || result?.submission?.address) && (
                      <p className="text-sm flex items-start gap-2 mt-1"><Mail className="w-4 h-4 mt-0.5" />{app.addressed_to?.address || result?.submission?.address}</p>
                    )}
                    {(app.addressed_to?.fax || result?.submission?.fax) && (
                      <p className="text-sm flex items-start gap-2 mt-1"><Phone className="w-4 h-4 mt-0.5" />Fax: {app.addressed_to?.fax || result?.submission?.fax}</p>
                    )}
                    {(app.addressed_to?.email || result?.submission?.email) && (
                      <p className="text-sm mt-1">Email: {app.addressed_to?.email || result?.submission?.email}</p>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Printable content */}
              <div ref={printRef} className="space-y-1">
                {/* Cover Letter */}
                {app.cover_letter && (
                  <SectionBlock title="Cover Letter" text={app.cover_letter}>
                    {app.cover_letter}
                  </SectionBlock>
                )}

                {/* Narrative */}
                {app.narrative && (
                  <SectionBlock title="Statement of Need / Narrative" text={app.narrative}>
                    {app.narrative}
                  </SectionBlock>
                )}

                {/* Budget */}
                {app.budget_justification && (
                  <SectionBlock title="Budget Justification" text={app.budget_justification}>
                    {app.budget_justification}
                  </SectionBlock>
                )}

                {/* Additional Sections */}
                {app.sections?.length > 0 && app.sections.map((sec, i) => (
                  <SectionBlock key={i} title={sec.section_name || `Section ${i + 1}`} text={sec.content}>
                    {sec.content}
                  </SectionBlock>
                ))}
              </div>

              {/* Submission Checklist */}
              {app.submission_instructions?.length > 0 && (
                <Card className="bg-green-50 border-green-200">
                  <CardContent className="p-4">
                    <h4 className="font-semibold text-green-900 flex items-center gap-2 mb-3">
                      <CheckCircle2 className="w-4 h-4" /> Submission Checklist
                    </h4>
                    <ol className="text-sm text-green-800 space-y-2 list-decimal list-inside">
                      {app.submission_instructions.map((step, i) => (
                        <li key={i} className="leading-relaxed">{step}</li>
                      ))}
                    </ol>
                  </CardContent>
                </Card>
              )}

              {/* Missing Items */}
              {app.missing_items?.length > 0 && (
                <Card className="bg-amber-50 border-amber-200">
                  <CardContent className="p-4">
                    <h4 className="font-semibold text-amber-900 flex items-center gap-2 mb-3">
                      <AlertTriangle className="w-4 h-4" /> Items You Still Need
                    </h4>
                    <ul className="text-sm text-amber-800 space-y-1.5">
                      {app.missing_items.map((item, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <Badge variant="outline" className="shrink-0 text-xs bg-amber-100">{i + 1}</Badge>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}
            </div>
          )}
        </ScrollArea>
      </SheetContent>
    </Sheet>
  );
}
