const path = require('path');
const { BaseCrawler, DEFAULT_TIMEOUT_MS, DEFAULT_MAX_RETRIES } = require('./base');

let Database;
try {
  // Prefer better-sqlite3 when available; fall back to no-op persistence otherwise.
  // eslint-disable-next-line global-require
  Database = require('better-sqlite3');
} catch (_) {
  Database = null;
}

const ALL_STATES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'DC',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
  'PR',
  'VI',
  'GU',
  'AS',
];

/**
 * Placeholder zip code mapping; expect real configuration to override.
 */
const STATE_ZIP_MAP = new Map();

const INSERT_OPPORTUNITY_SQL = `
  INSERT INTO funding_sources (
    state,
    zip_code,
    title,
    description,
    amount,
    deadline,
    contact_url,
    source_url,
    created_at,
    updated_at
  ) VALUES (
    @state,
    @zip,
    @title,
    @description,
    @amount,
    @deadline,
    @contactUrl,
    @sourceUrl,
    datetime('now'),
    datetime('now')
  )
  ON CONFLICT(state, zip_code, title) DO UPDATE SET
    description = excluded.description,
    amount = excluded.amount,
    deadline = excluded.deadline,
    contact_url = excluded.contact_url,
    source_url = excluded.source_url,
    updated_at = datetime('now')
`;

class LocalFundingCrawler extends BaseCrawler {
  constructor(options = {}) {
    const {
      states = ALL_STATES,
      timeoutMs = DEFAULT_TIMEOUT_MS,
      maxRetries = DEFAULT_MAX_RETRIES,
      logger = console,
      dbPath = path.join(__dirname, '..', 'data', 'grantflow.db'),
      db = null,
    } = options;

    super({
      items: states,
      timeoutMs,
      maxRetries,
      logger,
    });

    this.db =
      db || (Database ? new Database(dbPath, { fileMustExist: false }) : null);
    this.insertStmt = this.db ? this.db.prepare(INSERT_OPPORTUNITY_SQL) : null;
  }

  /**
   * Crawl a state by iterating its zip codes.
   * Each zip code error is logged and skipped.
   */
  async crawl(stateCode) {
    const zipCodes = STATE_ZIP_MAP.get(stateCode) || [];
    if (!zipCodes.length) {
      this.logger.warn(`[Crawler] No zip codes configured for ${stateCode}`);
      return;
    }

    for (const zip of zipCodes) {
      try {
        // eslint-disable-next-line no-await-in-loop
        const opportunities = await this.fetchOpportunitiesForZip({
          stateCode,
          zip,
        });

        if (opportunities.length) {
          this.saveOpportunities(stateCode, zip, opportunities);
          this.incrementOpportunities(opportunities.length);
        }
      } catch (error) {
        this.logger.error(
          `[Crawler] Error on ${stateCode}-${zip}, skipping: ${error.message}`,
        );
        this.errors.push({
          item: `${stateCode}-${zip}`,
          error: error.message,
        });
      }
    }
  }

  /**
   * Fetch opportunities for the given zip code.
   * Override to provide actual fetch logic.
   */
  // eslint-disable-next-line class-methods-use-this
  async fetchOpportunitiesForZip({ stateCode, zip }) {
    // Placeholder implementation – replace with real HTTP/database logic.
    return [
      {
        title: `Sample Opportunity ${stateCode}-${zip}`,
        description:
          'Placeholder opportunity generated by LocalFundingCrawler.',
        amount: null,
        deadline: null,
        contactUrl: null,
        sourceUrl: null,
      },
    ];
  }

  /**
   * Persist opportunities to the database (if configured).
   */
  saveOpportunities(stateCode, zip, opportunities) {
    if (!this.insertStmt) {
      this.logger.warn('[Crawler] No database configured; skipping persistence');
      return;
    }

    const insertMany = this.db.transaction((records) => {
      for (const record of records) {
        this.insertStmt.run({
          state: stateCode,
          zip,
          title: record.title,
          description: record.description,
          amount: record.amount,
          deadline: record.deadline,
          contactUrl: record.contactUrl,
          sourceUrl: record.sourceUrl,
        });
      }
    });

    insertMany(opportunities);
  }
}

module.exports = {
  LocalFundingCrawler,
  ALL_STATES,
  STATE_ZIP_MAP,
};

